powersync-ja/powersync-js

.changeset/pre.json
.gitignore

This PR puts Changesets into a prerelease mode in order to keep package versions consistent with the current `-alpha.x` versioning. 
Running `changeset version` in the next version PR will bump packages as below

[Workflow] Changesets prerelease

---

.changeset/config.json
.changeset/pre.json
.changeset/strong-waves-teach.md
.github/workflows/build-packages.yaml
.github/workflows/dev-packages.yaml
.github/workflows/release.yml
.gitmodules
README.md
package.json
packages/powersync-react/package.json
packages/powersync-sdk-common/package.json
packages/powersync-sdk-react-native/README.md
packages/powersync-sdk-react-native/package.json
packages/powersync-sdk-react-native/tsconfig.json
yarn.lock

This PR bumps the package versions to `0.0.1`, omitting the pre-release `-alpha.x` suffix which causes some issues with bumping versions and updating the latest homepage on NPMJS. 
The use of Git submodules is removed for `react-native-quick-sqlite`.
This updates the monorepo README to link to sub package READMEs.

[Chore] Update versions

---

.changeset/strong-moose-applaud.md
packages/powersync-sdk-common/src/client/sync/stream/AbstractRemote.ts
packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/powersync-sdk-react-native/README.md
packages/powersync-sdk-react-native/package.json
packages/powersync-sdk-react-native/src/sync/stream/ReactNativeRemote.ts

This PR adds some logging functionality which should assist with debugging. 
- Added display for exceptions that occur during the PowerSync instance streaming operations. 
- Added note to SDK README for configuring debug log levels.
- Added checks for HTTP streaming polyfills.

[Feature] Better Error Logging

---

.changeset/fair-planes-walk.md
packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/powersync-sdk-react-native/src/sync/stream/ReactNativeRemote.ts

This PR adds more frequent updates of sync status connectivity.

Update connectivity status

---

.changeset/itchy-jobs-return.md
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-react-native/src/db/PowerSyncDatabase.ts
yarn.lock

The work from https://github.com/powersync-ja/powersync-react-native-sdk/pull/25 introduced `waitForReady` on the PowerSyncDatabase client. This function should resolve once the client has been fully initialised.
The `waitForReady` method was previously responsible for setting the `AbstractPowerSyncDatabase.ready` member, but the `initialized` listener would only be registered once `waitForReady` had been called. If the `init` function had been called and completed before any `waitForReady` calls were made: the executed `waitForReady` function would never resolve as the `initialized` event would not be triggered again (init was already completed).
This issue was initially not detected in testing as (a logged in) test app contains watched queries which triggered  `waitForReady` and …

[Fix] Init Regression

---

.changeset/moody-hotels-happen.md
packages/powersync-sdk-common/src/client/sync/bucket/OplogEntry.ts
packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/powersync-sdk-common/src/client/sync/stream/streaming-sync-types.ts

This uses the `raw_data` mode when connecting to PowerSync instances. 
The raw data mode assists with better server and client side performance.

[Update] Raw Data

---

.changeset/smart-suns-divide.md
packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
yarn.lock

Currently when offline failed CRUD operations will immediately re-request upload, which is not ideal.
This adds a retry delay for failed CRUD upload operations.

[Fix] Upload crud delay

---

.changeset/dull-radios-relate.md
.changeset/gold-hairs-repair.md
packages/powersync-attachments/README.md
packages/powersync-react/README.md
packages/powersync-sdk-common/README.md
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-common/src/client/AbstractPowerSyncOpenFactory.ts
packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/powersync-sdk-common/src/db/DBAdapter.ts
packages/powersync-sdk-common/src/db/crud/SyncStatus.ts
packages/powersync-sdk-react-native/README.md
packages/powersync-sdk-react-native/package.json
packages/powersync-sdk-react-native/src/db/adapters/react-native-quick-sqlite/RNQSDBAdapter.ts
packages/powersync-sdk-react-native/src/db/adapters/react-native-quick-sqlite/RNQSDBOpenFactory.ts
yarn.lock

This PR introduces some improvements for the sync locking and status flows. This PR also adds changesets to release out of Beta to v1.0.0
The SyncStatus now includes the state of if the connector is uploading or downloading data.
Crud uploads are now debounced.
Crud uploads now are also triggered on `execute` methods.
Database name is now added to the `DBAdapter` interface for better identification in locks (for Web SDK)
Failed crud uploads now correctly throw errors, to be caught upstream, and delayed for retry.

[Improvement] Better locks and Sync

---

.changeset/polite-grapes-cover.md
packages/powersync-attachments/README.md
packages/powersync-attachments/src/AbstractAttachmentQueue.ts
packages/powersync-attachments/src/StorageAdapter.ts

Change `AbstractAttachmentQueue` implementation to not save the full URI in the `attachments` table, instead create it when needed.
When running the app in iOS Simulator, the reference to local storage is a directory generated for each debug device and would cause an error to be thrown, when the app tries to read the file. 
Example:
`
Error: File 'file:///Users/myuser/Library/Developer/CoreSimulator/Devices/060C2A66-D025-4C79-A77A-BE20DB439D0F/data/Containers/Data/Application/BEDD6677-78EF-4198-8655-9CDA98B71BB1/Documents/attachments/7b0630be-963d-49c4-af8e-52dc817b5c95.jpg' isn't readable.
`
- `getLocalFilePathSuffix()` to only append a `filename` to the attachment directory name
- Change `getLocalUri` to take a `filePath` instead of a `filename`
Tested on iOS simulator <-> Android …

[Fix] Issues with localFileURI on iOS Simulator

---

.changeset/many-hairs-scream.md
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-common/src/client/AbstractPowerSyncOpenFactory.ts
packages/powersync-sdk-common/src/client/sync/bucket/BucketStorageAdapter.ts
packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/powersync-sdk-react-native/src/db/PowerSyncDatabase.ts
yarn.lock

Previously connector CRUD uploads were debounced on a trailing edge whenever a `execute` or `writeTransaction` method was called. Debouncing allows for larger batch operations to be executed inside the connector `uploadCrud` method.
The debouncing could cause large delays before the `uploadCrud` connector method is called if many writes are executed sequentially. This PR updates the debounced logic to a throttled method which will trigger the `uploadCrud` method periodically during such periods of writes. 
The triggering of CRUD uploads has also been improved by watching for `ps_crud` table changes instead of running each time `execute` is called.

[Improvement] CRUD Upload Triggers

---

.changeset/angry-foxes-hammer.md
.changeset/fast-chicken-vanish.md
.gitmodules
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-common/src/db/DBAdapter.ts
packages/powersync-sdk-react-native/package.json
packages/powersync-sdk-react-native/src/db/adapters/react-native-quick-sqlite/RNQSDBAdapter.ts
yarn.lock

This PR fixes a bug where watched queries would sometimes fail to reflect updates from `writeTransaction`s.
Watched queries don't update due to a race condition where the table change hook is fired before the changes have been committed. The read connections re-execute watched queries, but don't return the latest updates. 
This builds off the work from https://github.com/powersync-ja/react-native-quick-sqlite/pull/13 which adds new methods for receiving table change updates once changes have been committed to the DB.
The common `DBAdapter` interface has been updated in order to be compatible with the previous DB connection API for single table updates and the recently updated Batch updates. 
This was tested using the React Native Todolist app. 
With the current SDK certain operations only …

[Fix] Watched query updates

---

demos/powersync-supabase-yjs-text-collab-demo/README.md

Remove link to obsolete archived repo

Update Yjs demo README.md to remove incorrect link

---

README.md

Rename the main README of powersync-js to be no longer describe the repo as being for React Native only

Monorepo updates to main README.md

---

packages/powersync-react/src/hooks/usePowerSyncQuery.ts
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-common/src/client/AbstractPowerSyncOpenFactory.ts
packages/powersync-sdk-common/src/client/connection/PowerSyncBackendConnector.ts
packages/powersync-sdk-common/src/client/sync/bucket/CrudBatch.ts
packages/powersync-sdk-common/src/client/sync/bucket/CrudEntry.ts
packages/powersync-sdk-common/src/client/sync/bucket/CrudTransaction.ts
packages/powersync-sdk-common/src/client/sync/bucket/SqliteBucketStorage.ts
packages/powersync-sdk-common/src/db/DBAdapter.ts
packages/powersync-sdk-common/src/db/crud/SyncStatus.ts
packages/powersync-sdk-common/src/db/crud/UploadQueueStatus.ts

JSDoc comments for JS

---

.changeset/little-bikes-sort.md
.changeset/sharp-lamps-perform.md
demos/react-native-supabase-todolist/ios/Podfile.lock
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-react-native/src/sync/stream/ReactNativeRemote.ts

This PR fixes two issues.
This fixes the issue mentioned here https://github.com/powersync-ja/powersync-js/issues/48.
The `transactionId` field is now correctly populated in the response of `getNextCrudTransaction`.
See the sample response from the Todolist demo app when deleting a todolist and items.
```JSON
{
"crud": [
{
"op_id": 20,
"op": "DELETE",
"type": "todos",
"id": "8cb587dd-948f-4eca-a4f9-0c31687e8d2e",
"tx_id": 17
},
{
"op_id": 21,
"op": "DELETE",
"type": "todos",
"id": "7720bf62-364c-467a-a787-1fe7526b94a0",
"tx_id": 17
},
{
"op_id": 22,
"op": "DELETE",
"type": "todos",
"id": "8ea4c802-7d2c-4554-aeef-21e7a2c46595",
"tx_id": 17
},
{
"op_id": 23,
"op": "DELETE",
"type": "todos",
"id": "f9718c7a-e4ad-4e86-b2d8-d96f85503175",
"tx_id": 17
},
{
"op_id": 24,
"op": "DELETE",
"type": …
```

[Fix] Missing transactionId value + Reconnect Issue

---

demos/react-native-supabase-todolist/android/build.gradle
demos/react-native-supabase-todolist/android/gradle/wrapper/gradle-wrapper.properties

`com.facebook.react:react-native-gradle-plugin` currently depends on `com.android.tools.build:gradle:8.1.1`. This updates it to 8.2.2, to support OpenJDK 21. (OpenJDK 22+ is not supported by the current Gradle release yet).
This version bump should be included in react-native 0.74 when released: https://github.com/facebook/react-native/commit/a7586947d719a9cd2344ad346d271e7ca900de87
Upstream issue fixed by the update: https://issuetracker.google.com/issues/294137077
Fixes #55.

OpenJDK 21

---

.changeset/pink-rings-retire.md
.changeset/sharp-meals-join.md
.changeset/small-pianos-clap.md
packages/powersync-sdk-common/package.json
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-common/src/client/sync/bucket/CrudEntry.ts
pnpm-lock.yaml

It was recently discovered in the YJS NextJS demo app that watched uploads would take long to trigger if multiple Powersync instances were created for the same DB. This was due to the sync status not being correctly shared between the (multiple) instances. The second instance would not trigger uploads since it did not know a connection to the PowerSync instance was established by the first instance. 
This same issue would manifest itself in regular apps (with a single instance per tab). Sync statuses between multiple tabs would not be shared. Subsequently opened tabs would remain in `connected: false` mode. 
The root cause of this issue was that the `SharedSyncImplementation.worker.ts` shared worker failed to run and share syncing information between tabs and instances. The worker thew an …

[Fix] Shared sync

---

.changeset/twenty-cups-cover.md
demos/react-native-supabase-todolist/ios/Podfile.lock
demos/react-native-supabase-todolist/ios/powersyncexample.xcodeproj/project.pbxproj
demos/react-native-supabase-todolist/library/powersync/system.ts
demos/react-native-supabase-todolist/library/widgets/TodoItemWidget.tsx
demos/react-native-supabase-todolist/package.json
packages/powersync-attachments/src/AbstractAttachmentQueue.ts
pnpm-lock.yaml

Add handlers to allow user to deal with `uploads` and `downloads`
* Added `onDownloadError` and `onUploadError` optional options 
* Updated demo app to showcase an example of how to use it
It's easiest to test this through the demo todo-list app.
* Delete an attachment from supabase bucket that is connected to a todo item you have
* Run the app
* You should not see an error for the download
* Go to `system.ts` and change the `{ retry: true }` in `onDownloadError` to `{ retry: false }`. Reload the app, you should see the error

feat(attachments): add error handlers

---

demos/example-vite/package.json
demos/example-vite/src/index.js
demos/example-vite/vite.config.ts
pnpm-lock.yaml

This adds more Vite config which ensures that shared web workers are correctly bundled. 
The example Vite demo now attempts to `connect` in order to verify that the Shared Sync worker loads correctly. 
This is based off the work shown here https://github.com/powersync-ja/powersync-web-sdk/issues/16#issuecomment-1890776880

[Demo] Vite Example

---

.changeset/great-boxes-mate.md
demos/nextjs-supabase-todolist/README.md
demos/react-native-supabase-todolist/README.md
demos/yjs-nextjs-supabase-text-collab/sync-rules.yaml
packages/powersync-attachments/package.json
packages/powersync-react/package.json
packages/powersync-sdk-common/README.md
packages/powersync-sdk-common/package.json
packages/powersync-sdk-react-native/README.md
packages/powersync-sdk-react-native/package.json
packages/powersync-sdk-web/README.md
packages/powersync-sdk-web/package.json
packages/powersync-sdk-web/src/db/adapters/wa-sqlite/WASQLiteDBAdapter.ts
packages/powersync-sdk-web/src/worker/db/SharedWASQLiteDB.worker.ts
packages/powersync-sdk-web/src/worker/sync/SharedSyncImplementation.worker.ts
packages/powersync-sdk-web/tsconfig.json

Minor improvements to the repo
* Removed unused package imports
* Add .com instead of .co
* Changed to use lib instead of dist for web-sdk as this is the repos convention

chore: minor improvements

---

demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/ios/Podfile.lock
demos/react-native-supabase-todolist/package.json
packages/powersync-sdk-react-native/package.json
pnpm-lock.yaml

This updates the package version of react-native-quick-sqlite in our demos. This follows changes from https://github.com/powersync-ja/react-native-quick-sqlite/pull/19.
The React Native SDK uses this package as a peer dependency. So no updated package publish should be required.

[Demos] Update react-native-quick-sqlite

---

packages/kysely-driver/README.md

Kysely README.md

---

.changeset/lemon-zoos-sort.md
.changeset/lucky-planes-prove.md
.changeset/modern-terms-admire.md
packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/powersync-sdk-web/src/db/sync/SharedWebStreamingSyncImplementation.ts
packages/powersync-sdk-web/src/worker/sync/BroadcastLogger.ts
packages/powersync-sdk-web/src/worker/sync/SharedSyncImplementation.ts

This fixes an issue where sync stream connections would not be closed if any exceptions were thrown while handling events from the backend instance.
Previous connections are now closed before new connections are established. 
This PR also includes some fixes for the shared sync worker's broadcast logger.
Testing:
The network graph below shows how connections are closed on error.

[Fix] concurrent connections issue

---

.changeset/metal-vans-grin.md
.changeset/shaggy-apples-lick.md
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-web/src/db/sync/SharedWebStreamingSyncImplementation.ts
packages/powersync-sdk-web/src/worker/sync/SharedSyncImplementation.ts
packages/powersync-sdk-web/tests/watch.test.ts

This fixes a regression from https://github.com/powersync-ja/powersync-js/pull/90 which caused watched queries to update on any data table change instead of tables specified in the query or options.
This also pre-emptively does some code cleanup in the shared sync manager code. 
Before: The watched query for the `lists` table would update even when a change was made to the `todos` table 
https://github.com/powersync-ja/powersync-js/assets/51082125/40674d05-6de9-42f9-8c74-7d223578eb02
After: the lists query does not retrigger for external updates
https://github.com/powersync-ja/powersync-js/assets/51082125/20f4faaf-7a3f-40a4-9f77-d3c44d521c17

[Fix] Watched queries retriggers

---

.changeset/clever-phones-hang.md
.changeset/heavy-dogs-work.md
.changeset/slow-years-pull.md
.changeset/sweet-pumpkins-explain.md
demos/react-native-supabase-todolist/library/powersync/PhotoAttachmentQueue.ts
packages/powersync-attachments/README.md
packages/powersync-attachments/src/AbstractAttachmentQueue.ts
packages/powersync-react/src/hooks/usePowerSyncWatchedQuery.ts
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
packages/powersync-sdk-web/src/db/sync/SharedWebStreamingSyncImplementation.ts
packages/powersync-sdk-web/src/worker/sync/SharedSyncImplementation.ts
packages/powersync-sdk-web/tests/multiple_instances.test.ts
packages/powersync-sdk-web/tests/watch.test.ts

A suggestion was made to add a callback support to the `watch` and `onChange` methods which can be used over the existing AsyncIterator approach. Which we would likely want to use instead when we add new js packages (Vue etc). This is introduced as overloaded versions of the existing functions, which means existing usage of the existing `watch` and `onChange` should be unaffected.
Usage with existing AsyncIterator signature:
```typescript
for await (const result of powerSync.watch(sqlStatement, parameters, {
...options,
signal: abortController.signal
})) {
data = result.rows?._array ?? [];
}
```
Usage with new overloaded signature:
```typescript
powerSync.watch(sqlStatement, parameters, {
onResult(results) {
data = results.rows?._array ?? [];
},
onError(e) { } // onError is optional
}, { …
```

[Update] powersync-sdk-common: watch/onChange API overloads to support callbacks

---

demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/package.json
packages/powersync-sdk-react-native/package.json
pnpm-lock.yaml

Bumps up all `@journeyapps/react-native-quick-sqlite` dependencies to the latest v1.1.3.

Upgrade react-native-quick-sqlite to 1.1.3

---

packages/powersync-sdk-react-native/README.md

Some newer version of dependencies have been released, namely `web-streams-polyfill` 4.0 and `react-native-get-random-values` 1.11 which break installation. 
This PR locks to known good values.

RN: lock package versions in README

---

.changeset/rare-pumpkins-study.md
packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts

Fumbled `this` usage. Issue occurred when an onError handler wasn't specified for a watched query.

fix default onError callback values for watch() and onChange()

---

demos/react-native-supabase-todolist/library/supabase/SupabaseConnector.ts
demos/react-supabase-todolist/src/library/powersync/SupabaseConnector.ts
demos/vue-supabase-todolist/src/library/powersync/SupabaseConnector.ts
demos/yjs-react-supabase-text-collab/src/library/powersync/SupabaseConnector.ts

client is not a required property and is not used in `fetchCredentials` implementation of the demos and should be removed

chore: remove client property from fetchCredentials

---

.changeset/clever-kiwis-lay.md

This wasn't picked up as a conflict. Should be a simple rename.

fix: mentioned packages in change file were outdated

---

.changeset/tame-chefs-flash.md
demos/django-react-native-todolist/package.json
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/package.json
packages/react-native/package.json
pnpm-lock.yaml

Verified todo app still works on a clean install (with 10k+ todos).

chore: Updated react-native-quick-sqlite depedency to 1.1.5

---

.changeset/metal-cheetahs-try.md
packages/kysely-driver/src/sqlite/sqlite-connection.ts
packages/kysely-driver/src/sqlite/sqlite-driver.ts
packages/kysely-driver/tests/sqlite/db.test.ts

Make `releaseConnection` and `destroy` no-ops to fix issue where `execute` was resulting in the PowerSync DB being closed.
* Made `releaseConnection` a no-op
* Made `destroy` a no-op

fix: kysely closing db on execute

---

demos/react-native-supabase-todolist/library/powersync/system.ts
demos/react-native-supabase-todolist/library/widgets/HeaderWidget.tsx

At the moment react native supabase todolist demo assumes there will always be a bucket to handle attachments, we need to cater for the case where there is no bucket configured
* Added check for supabase bucket
* Added check to only trigger queue if one exists in header widget
* Load react native supabase todolist demo
* Click wifi icon

chore: handle no attachment queue

---

.changeset/unlucky-hats-cover.md
packages/common/src/client/AbstractPowerSyncDatabase.ts

Improve `hasSynced` to be set on `connect` method.
* Updated `hasSynced` so that it is set when status changes in connect
* Load the app without any data you should see the `Busy syncing data` text change once sync has occurred

chore(common): improve hasSynced

---

.changeset/heavy-dancers-drum.md
.changeset/proud-falcons-lay.md
demos/angular-supabase-todolist/angular.json
demos/django-react-native-todolist/library/stores/AbstractStore.ts
demos/django-react-native-todolist/package.json
demos/example-electron/vite.renderer.config.ts
demos/example-nextjs/package.json
demos/example-vite/vite.config.ts
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/library/powersync/PhotoAttachmentQueue.ts
demos/react-native-supabase-todolist/package.json
demos/react-supabase-todolist/vite.config.mts
demos/vue-supabase-todolist/package.json
demos/vue-supabase-todolist/vite.config.ts
demos/yjs-react-supabase-text-collab/package.json
packages/common/package.json
packages/common/src/client/sync/bucket/SqliteBucketStorage.ts
packages/common/src/utils/BaseObserver.ts
packages/react-native/README.md
packages/react-native/package.json
packages/web/package.json
packages/web/src/worker/db/SharedWASQLiteDB.worker.ts
packages/web/src/worker/db/open-db.ts
pnpm-lock.yaml

This helps to reduce build issues, especially for react-native which needs `react-native-get-random-values` for that.
Most of the places we use it is in-memory only can be replaced by a simple incrementing integer id.
`deleteBucket` is slightly more complex, but we can let SQLite generate a uuid for us in that case.
Some demos still use `uuid` in other places, but none of the core packages should need it anymore.
Also see https://github.com/powersync-ja/react-native-quick-sqlite/pull/31.

Remove uuid and react-native-get-random-values dependencies

---

.changeset/rich-steaks-bake.md
.changeset/thirty-chicken-kick.md

https://github.com/powersync-ja/powersync-js/pull/158 Contained some outdated package names in changesets.

[Fix] Changesets Update packages

---

.changeset/tasty-teachers-switch.md
packages/attachments/package.json
packages/kysely-driver/package.json
packages/react-native/package.json
packages/react/package.json
packages/vue/package.json
packages/web/package.json
pnpm-lock.yaml

Add common to peerDependency of packages so that users are warned if common is mismatched under breaking change.
There is no need to have common a dependency anymore as peerDeps are auto installed in npm and pnpm and a warning is given in yarn.
**Example warning in NPM and Yarn (using an example from the internet)**:
**Notes:**
* There is a possibility to use changesets to update peerDeps but that appears to have issues as outlined here https://github.com/changesets/changesets/issues/1011
* NPM, PNPM and Yarn handle these differently. There seems to be an issue with PNPM not adhering to the peerDeps as mentioned here [pnpm does not fail when missing peer deps with strict-peer-dependencies](https://github.com/pnpm/pnpm/issues/6893)

chore: add common as peer dependency to packages

---

.changeset/config.json
packages/attachments/package.json
packages/kysely-driver/package.json
packages/react-native/package.json
packages/react/package.json
packages/vue/package.json
packages/web/package.json
pnpm-lock.yaml

Add `"updateInternalDependents": "out-of-range"` option to changeset config so that underlying dependencies (e.g. `@powersync/react` are only updated when `@powersync/common` is major version updated.
I have further changed the dependency range to be more specific by using `>= 1.7.0 < 2`.
This has been tested locally to verify that it works as expected. 
**Example**:  if you have 
```  
"name": "@powersync/react",
"version": "1.3.3",
"peerDependencies": {
"@powersync/common": "workspace:>= 1.7.0 < 2"
},
```
And you do a minor or patch version update to `@powersync/common` the package that has the above peerDependencies will not require a version bump. However if you do a major version bump to `@powersync/common` then it will be changed to 
```  
"name": "@powersync/react",
"version": …
```

chore: update dependency range and changeset config

---

.changeset/curly-penguins-march.md
README.md
demos/vue-supabase-todolist/README.md
packages/vue/README.md

Bump Vue composables package to beta after a period of testing.
No updates were necessary besides references to "alpha release".

Upgrade Vue support into beta

---

docs/utils/packageMap.ts

This removes `common-sdk` from the docs.
After an internal discussion, we came to a realization that having `common-sdk` in the JS Docs is not necessary as the SDK's that require `common-sdk` already have the relevant properties in their documentation due to them re-exporting `@powersync/common` and thus `common-sdk` adds unnecessary repetition.

chore(docs): remove common

---

docs/src/css/custom.css

The style changes to tables in docs have not been applied to the properties table. This change adds those.

chore(docs): update properties table styling

---

.github/workflows/release.yml
pnpm-lock.yaml

Recently the Github actions have sometimes been failing after the Changeset version pull request has been merged due to PNPM lockfile issues https://github.com/powersync-ja/powersync-js/actions/runs/9397015900.
This PR updates the lockfile and also adds a step to update the lockfile automatically after Changesets has versioned packages.

[Fix] Lockfile update

---

.changeset/famous-teachers-design.md
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/web/tests/stream.test.ts
packages/web/tests/utils/MockStreamOpenFactory.ts

A bug was recently discovered where CRUD uploads would not retry (for a long time) after failing when using the WebSocket connection method. 
This was due to a failed upload updating the connection status to `connected: false`. Following CRUD loop iterations would check the connection status and exit if not connected. 
The connection status is usually updated to `true` whenever a sync event is received from the PowerSync backend server. For the HTTP method keep-alive events are sent at regular intervals which will update the status back to `connected: true`. This is not the case for WebSockets as that method handles keep-alive events internally. 
This PR aligns the CRUD upload connection status logic with the Dart SDK. The connection status is not set to `false` if an upload fails. It is …

[Fix] CRUD upload retries

---

.github/workflows/release.yml
package.json

This PR is a follow up to https://github.com/powersync-ja/powersync-js/pull/203. From the latest [action run](https://github.com/powersync-ja/powersync-js/actions/runs/9444115848/job/26009056296) the Changeset `version` command does not parse `&&` commands well. 
The PNPM lockfile update command has been updated to a PNPM script which is usable as a Changeset command.
This has been tested and verified [here](https://github.com/powersync-ja/changesets-slave)

[Chore]: fix Changeset version action

---

.changeset/short-snails-visit.md
packages/vue/src/composables/useQuery.ts
packages/vue/tests/useQuery.test.ts

Vue wraps its reactive variables in Proxy objects. It seems there's a point at which we provide these objects to comlink (in the sharedWorker I believe) where it fails to parse the input. This PR ensures that the SQL parameters are raw when it reaches that point.
According to Discord user who reported this [issue](https://discord.com/channels/1138230179878154300/1138251135929548850/threads/1258980918895575120), the changeset fixes this problem (tested via dev package publish).

[Fix] Vue useQuery comlink error caused when using reactive sql parameters

---

.changeset/happy-gifts-sort.md
tools/diagnostics-app/src/app/views/sync-diagnostics.tsx
tools/diagnostics-app/src/library/powersync/ConnectionManager.ts
tools/diagnostics-app/src/library/powersync/RecordingStorageAdapter.ts

This makes the initial sync significantly faster in the diagnostics app.
The main issue was the queries scanning the entire oplog, every time a batch of data was downloaded. Those queries were often significantly slower than the saving of the data itself. And since the web SDK does not support concurrent reads, it slowed down the entire initial sync.
This now runs a much faster query (with less stats) during initial sync, then switches over to the full queries after that.
This also increases the SQLite cache size for the diagnostics app, which makes those same queries run much faster.
This also contains other minor fixes, such as fixing issues in the stats calculations (which were mostly relevant during initial sync so not that relevant anymore), improving the loader UI, and using …

Diagnostics app improvements

---

.changeset/healthy-insects-push.md
packages/attachments/package.json
packages/kysely-driver/package.json
packages/react-native/package.json
packages/react/package.json
packages/vue/package.json
packages/web/package.json
pnpm-lock.yaml

There appears to be an issue with pnpm update (https://github.com/pnpm/pnpm/pull/7633/files) which has resulted in `workspace` changing behaviour when publishing. As a result it duplicates the package version resulting in something like `1.3.0^1.3.0`. We are therefore changing the `peerDeps` range to use `^` and removing the version number i.e. no longer `^1.3.0` and just `^`.
When the packages are updated this should resolve this https://github.com/powersync-ja/powersync-js/issues/231

chore: update @powersync/common peer dep range

---

.changeset/pretty-zebras-brush.md
packages/common/src/client/sync/stream/AbstractRemote.ts

RSocket allows for multiple endpoints to be handled over a single connection. We currently only use a connection to perform a single `stream` request to the `sync/stream` route.  
RSocket will close the `stream` on error, but it won't close the main connection. This means under some circumstances, such as `stream` authentication errors, the WebSocket won't be closed by the client. 
This PR updates the logic to close the connection and WebSocket whenever an error occurs. Extra logic is added to cater for cases where the `stream` is not accepted by the server.
This was tested locally by logging the number of active WebSocket connections during various error states.
Before (without changes from https://github.com/powersync-ja/powersync-service/pull/45): The number of active clients would …

[Fix] WebSocket close bug

---

.changeset/spicy-poems-complain.md
packages/common/src/client/SQLOpenFactory.ts
packages/web/src/db/adapters/wa-sqlite/WASQLiteDBAdapter.ts
tools/diagnostics-app/src/library/powersync/ConnectionManager.ts

This displays all SQL queries on the performance timeline. Currently only implemented in the Web SDK.
This excludes the time waiting for the global transaction lock, but includes all overhead in worker communication. This means you won't see concurrent queries in most cases.
This includes internal statements from PowerSync, including queries saving sync data, and begin/commit statements. It does not include internal statements from powersync-sqlite-core.
TODO:
* ~The flag currently defaults to false if `process.env.NODE_ENV == 'production'`, similar to what React does. All other cases default to true. Should we perhaps be more conservative and require explicit opt-in, since the queries could be considered semi-sensitive data?~ Updated default to false, requiring explicit opt-in for now. …

Add a debugMode flag to log queries to the performance timeline

---

.changeset/config.json

The demo packages make version bump pull requests become very verbose on simple changes to `@powersync/common` or similar core packages. See an example [here](https://github.com/powersync-ja/powersync-js/pull/236).
This excludes demos from changesets completely. This means we'll have to manually manage changelots for those when we do make significant changes.

Ignore demos for changesets

---

.changeset/shaggy-walls-hang.md
.github/workflows/release.yml
packages/attachments/package.json
packages/kysely-driver/package.json
packages/react-native/package.json
packages/react/package.json
packages/vue/package.json
packages/web/package.json
pnpm-lock.yaml

We need to revert this previous PR https://github.com/powersync-ja/powersync-js/pull/235 as it is causing changesets to make major version updates.
In order to avoid the previous issue where e.g, `workspace:^1.2.0` is changed to `1.2.0^1.2.0`, this PR also reduces the pnpm version for the release github action to use `pnpm 9.3` as `9.4` and newer introduces the issue.

chore: revert @powersync/common peer dep workspace change

---

.changeset/mean-carrots-relax.md
demos/react-native-supabase-todolist/ios/Podfile.lock
packages/common/src/client/sync/bucket/BucketStorageAdapter.ts
packages/common/src/client/sync/bucket/SqliteBucketStorage.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/web/tests/multiple_instances.test.ts

Currently when processing CRUD items the `PowerSyncDatabase` client will call the backend connector's `uploadData` function whenever `CrudEntry` items are present in the `ps_crud` internal table.
The `uploadData` callback has access to the `PowerSyncDatabase` client which it can use to get the pending `CrudEntry`s. The connector can consume the CRUD events in numerous different ways. 
Typically the `uploadData` callback will either call `getNextCrudTransaction` or `getCrudBatch` on the `PowerSyncDatabase`. 
- `getNextCrudTransaction` will return the next (Single) group of `CrudEntry`s which occurred in the same transaction as an instance of `CrudTransaction`. If an  operation did not occur in a transaction then only a single operation will be returned. 
- `getCrudBatch` returns `n` …

[Feature] Add warning if crud transactions are not completed

---

.changeset/breezy-crews-fry.md
packages/web/src/db/sync/SharedWebStreamingSyncImplementation.ts
packages/web/src/worker/sync/SharedSyncImplementation.ts

This fixes a bug when using multiple tab functionality where: the Shared sync manager would "hold on" to credentials previously provided to it. This was due to the shared worker previously mainlining a single instance of `AbstractStreamingSyncImplementation`. This implementation would use cached credentials until they expired. This is particularly bad if the tab remains open after `disconnectAndClear` has been called and the user has "signed out".
Most of our SDKs currently create a new instance of the StreamingSync implementation on each `connect` call. This effectively will clear any caches. 
The shared sync manager now creates the streaming sync implementation when the `connect` call is invoked. This ensures the `fetchCredentials` of the `BackendConnector`  is called for each call to …

[Fix] Stale credentials in mulitple tabs

---

.changeset/red-suits-explode.md
tools/diagnostics-app/src/components/widgets/LoginDetailsWidget.tsx

* Support extracting the endpoint from a token with multiple audiences
* Support self-hosted / generic http endoints.
This can help to reduce friction slightly when using the diagnostics app for local development.

[diagnostics-app] support multiple audiences

---

tools/diagnostics-app/README.md

Better distinguish running the app locally vs signing in (latter is applicable to local and cloud setups)

Distinguish running the app vs signing in

---

.changeset/strange-feet-explain.md
packages/web/src/db/adapters/wa-sqlite/WASQLiteDBAdapter.ts
packages/web/src/shared/open-db.ts
packages/web/src/shared/types.ts

Firing update notifications for each individual row adds a massive performance overhead.
This change debounces the notifications, only sending a single event per table changed (we never exposed the row ids of changes to the end-user API anyway).
In some test scenarios this gives a 20-25x speedup in initial sync times, for example going from 240s -> 10s for 40k operations.

[web] debounce update notifications

---

.github/workflows/dev-packages.yaml

Right now deploying dev release action is called `Packages Deploy` which is not very intuative. This changes is to reflect what it is actually meant for which is `Create Dev Release`.

chore: rename action to be more intuative

---

.changeset/afraid-bulldogs-check.md
.changeset/hungry-eyes-enjoy.md
packages/common/src/client/constants.ts
packages/common/src/client/sync/bucket/CrudEntry.ts
packages/common/src/client/sync/bucket/SqliteBucketStorage.ts
packages/common/src/client/sync/bucket/SyncDataBucket.ts
packages/common/src/index.ts
packages/common/tsconfig.json

There is a runtime issue where enum values are not used because the enum values are ambient.
Added tsconfig option `preserveConstEnums`  to create enum values in JS file that can be used at runtime.

chore(common): improve enums export and clean up

---

.changeset/dull-dancers-judge.md
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/client/SQLOpenFactory.ts
packages/web/tests/open.test.ts

This adds some very basic checks for invalid options to the `PowerSyncDatabase` constructor. 
JavaScript users might incorrectly supply required options or fail to supply them at all. This should help those users identify issues. 
The warnings here are not detailed. But should be better than cryptic errors which could occur down-the-line if invalid arguments are provided.

[Feature] Added PowerSyncDatabase options validation

---

.changeset/green-dogs-clap.md
packages/react/README.md

This adds a basic example of using `isLoading` and `isFetching` to the `@powersync/react` README.

chore: added isLoading to docs

---

.changeset/pretty-waves-flow.md
packages/react-native/src/sync/stream/ReactNativeRemote.ts

A debug log is printed if using Android and the HTTP network request failed to resolve in 30 seconds. This is usually due to the Flipper debug tool causing HTTP stream requests to never resolve (or reject). The timeout for this log was cleared if the HTTP request resolves.
The Flipper warning log would still show after the timeout expired even if the network request rejected. This updates the logic to clear the timeout if the HTTP request rejects or resolves.
Verified that the timeout is cleared if the request resolves or rejects. HTTP streaming also functions normally.

[Fix] Flipper Warning

---

.github/workflows/build-docs.yaml
docs/package.json
packages/web/src/db/sync/userAgent.ts
pnpm-lock.yaml

This fixes a documentation build regression from #289.
To prevent this from happening in the future, documentation is now always built as part of the normal checks.

Fix documentation build

---

.changeset/nervous-ducks-develop.md
.changeset/orange-points-speak.md
packages/kysely-driver/src/sqlite/db.ts
packages/react/src/hooks/useQuery.ts
packages/react/tests/useQuery.test.tsx
packages/vue/src/composables/useQuery.ts
packages/vue/tests/useQuery.test.ts

Packages such as the Kysely driver provide a `.execute()` method on query objects. This execute method could perform pluggable modifications based on installed plugins. 
This PR allows the `useQuery` hooks and composibles from `@powersync/react` and `@powersync/vue` to use the `execute` method from compatible queries. 
Related issue: https://github.com/powersync-ja/powersync-js/issues/292
The `dialect` option in the  `wrapPowerSyncWithKysely` has been made optional since the method provides a PowerSync dialect by default.
This was verified with unit tests and by implementing a simple Kysely plugin which overwrites the query result.
```TypeScript
const k = wrapPowerSyncWithKysely<Database>(db, {
plugins: [
{
transformQuery: (p) => p.node as any,
transformResult: async (args) => {
return { …
```

[Fix] Custom Query Executor Hooks

---

.changeset/four-birds-raise.md
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/web/src/db/PowerSyncDatabase.ts
packages/web/src/db/adapters/AbstractWebSQLOpenFactory.ts
packages/web/src/db/sync/SSRWebStreamingSyncImplementation.ts

This fixes an issue where manually specifying `ssrMode: true` in the `PowerSyncDatabase` constructor `flags` could cause unexpected syncing behaviour to occur in the browser client.
Previously the `WASQLiteOpenFactory` did not account for the `ssrMode` flag. This would create a `DBAdapter` based on the detected environment. Specifying `ssrMode: true` would result in a functional `WASQLiteDBAdapter` being created (on the client). 
Previously the `SSRStreamingSyncImplementation` extended `AbstractStreamingSyncImplementation` which contains logic for processing sync commands from the server. Sync commands would be a `no-op` if the suppled `DBAdapter` was a placeholder SSR DBAdapter, but as described above this was not the case if `ssrMode: true` was specified.
The locks in …

[Fix] SSR Mode Detection

---

packages/common/src/db/schema/Table.ts

`Table` examples in JS Docs are broken
Fixed `Table` examples in JS Docs

docs: fix table examples

---

.changeset/afraid-apples-learn.md
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/web/src/db/PowerSyncDatabase.ts
packages/web/tests/stream.test.ts
packages/web/tests/uploads.test.ts
packages/web/tests/utils/MockStreamOpenFactory.ts

https://github.com/powersync-ja/powersync-js/pull/254 Added monitoring of the `ps_crud` CRUD upload operations. 
The monitoring relies on `ps_crud` rows being consumed and removed by the `BackendConnector` `uploadData` method. An upload delay is added if the CRUD entry at the head of the queue has not been changed between calls to `uploadData`.
The `ps_crud` table contains `id` and `data` columns. `id` Should be a unique incrementing integer while the `data` column contains JSON of the CRUD data change operation.
The raw `ps_crud` entry is parsed into a `CrudEntry` instance which exposes the data above. The mapping in the parsing maps `ps_crud:id` => `CrudEntry.clientId` and `ps_crud:data:id` to `CrudEntry.id`.
The previous implementation incorrectly assumed `CrudEntry.id` was the …

fix: CRUD Upload Queue Monitoring

---

demos/react-supabase-todolist-optional-sync/src/library/powersync/AppSchema.ts

Original issue reported in dart optional sync demo https://github.com/powersync-ja/powersync.dart/discussions/174.
This ensures that we correctly copy over the todos with the authed user ID instead of the default local ID.
Instead of copying the local data over to the sync table verbatim (and getting the owner ID from the local table), we use the newly logged in user's ID.

Optional Sync Demo: Fixed updating schema when moving todos to synced table

---

demos/react-native-supabase-todolist/README.md

Following the current instructions causes a bundling failure when running the demo. Updated the README to follow the same structure as react-supabase-todolist docs.

react-native-supabase-todolist doc update

---

packages/react-native/README.md

Added a note in the docs about `metro.config.js` changes that need to be made to get the package to work with non-Expo React Native projects. This should hopefully avoid these issues for users in the future https://discord.com/channels/1138230179878154300/1290949501049110623 and https://discord.com/channels/1138230179878154300/1194710422960472175/1290907741568765964

docs(react-native): add note about metro config

---

.changeset/few-jeans-prove.md
packages/react/src/hooks/useQuery.ts

Original issue reported at https://github.com/powersync-ja/powersync-js/issues/323.
Dynamic query dependencies would warn with the following if the query parameter array changed in size:
`Warning: The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant. Previous: [] Incoming: [xxxxxxxxxxxxx]
`
Tested with the following to verify that it works now:
```
const [params, setParams] = React.useState<string[]>([]);
const { data } = useQuery(`select * from lists where id=?`, params);
onclick:: setParams(["some-uuid"])
```
The change from `React.useMemo(() => {}, [...array]);` to `React.useMemo(() => {},[JSON.stringify(array)])` should not introduce any issues, as valid query parameters are expected to be serialisable.

[Fix] `packages/react` issue with `useQuery` not supporting dynamic query parameters

---

.changeset/tricky-moons-ring.md
packages/powersync-op-sqlite/android/build.gradle
packages/powersync-op-sqlite/powersync-op-sqlite.podspec

Follow-up to #334 to also update powersync-sqlite-core with `@powersync/op-sqlite`.

powersync-sqlite-core 0.3.0 for op-sqlite

---

.changeset/witty-starfishes-retire.md
packages/powersync-op-sqlite/package.json

Currently the package is published without the generated javascript lib files. This ensures that the files are built before the package is published.

Fix: Generate lib files before releasing @powersync/op-sqlite

---

.changeset/fifty-cars-laugh.md
packages/tanstack-react-query/package.json

Prod builds weren't being correctly kicked off for the `tanstack-react-query` package.

fix: tanstack-react-query prod build

---

.changeset/gorgeous-pens-give.md
packages/tanstack-react-query/src/hooks/useQuery.ts

Fixed issue with queries not reacting to local data changes and sometimes causing an infinite loop on certain sql parameters.
Both issues were related to parameters for `useQuery()/useSuspenseQuery()` triggering `useEffect` redundantly.

fix: Tanstack react query watch issues

---

.changeset/gentle-apricots-attack.md
demos/angular-supabase-todolist/package.json
demos/example-capacitor/package.json
demos/example-electron/package.json
demos/example-nextjs/package.json
demos/react-multi-client/package.json
demos/react-supabase-todolist-optional-sync/package.json
demos/react-supabase-todolist/package.json
demos/yjs-react-supabase-text-collab/package.json
packages/kysely-driver/package.json
packages/web/package.json
pnpm-lock.yaml
tools/diagnostics-app/package.json

This updates WA-SQLite to include the changes from [here](https://discord.com/channels/1138230179878154300/1297755170574172180/1300780159762432132).

[Chore] Update wa-sqlite patch

---

.github/workflows/audit.yaml
audit-ci.jsonc

Add audit check to GitHub pipeline basic checks. This uses [audit-ci](https://github.com/IBM/audit-ci) to check for critical vulnerabilities in this repo. If a vulnerability is critical it will fail the audit check resulting in the PR not being allowed to be merged due to checks needing to pass.
You can see the audit run here https://github.com/powersync-ja/powersync-js/actions/runs/11593616269/job/32278028624

chore: add audit check

---

.changeset/kind-cats-check.md
packages/powersync-op-sqlite/src/db/OPSqliteAdapter.ts

- 5 concurrent read-only connections
- Use a queue to manage queries when all connections are busy
- Process queued operations as soon as connections become available
Tested locally running multiple queries running at the same time with random delays between the queries.

Feat: Queue read connections OPSQLite

---

.changeset/perfect-zebras-marry.md
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/web/tests/crud.test.ts

This PR aligns the `getCrudBatch` method with the [Dart SDK](https://github.com/powersync-ja/powersync.dart/blob/84fc5649e8ebf71153fe041e2b5968d137ff78aa/packages/powersync/lib/src/database/powersync_db_mixin.dart#L327) by providing a default limit for the number of CRUD entries returned.

feat: getCrudBatch default limit

---

.changeset/big-ducks-peel.md
.gitignore
packages/kysely-driver/README.md
packages/kysely-driver/package.json
packages/kysely-driver/tests/setup/db.ts
packages/kysely-driver/tests/sqlite/db.test.ts
pnpm-lock.yaml

Added a test example and updated the docs to show how to use raw sql in a transaction (in case more users have this question https://discord.com/channels/1138230179878154300/1303135609011048551/1303139332730785802)
* Updated to kysely 0.27.4
* Updated dev deps
* Improved README 
* Cleaned up some imports
* Added a test case 
All unit tests are passing

chore: add kysely test example for transaction with raw sql and update deps

---

demos/django-react-native-todolist/package.json
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/package.json
demos/react-native-web-supabase-todolist/package.json
pnpm-lock.yaml

Demo version bumps on react-native-quick-sqlite to minimum `^2.1.0`.

Updated demos to use latest react-native-quick-sqlite version

---

.changeset/long-onions-double.md
demos/angular-supabase-todolist/package.json
demos/django-react-native-todolist/package.json
demos/example-capacitor/package.json
demos/example-electron/package.json
demos/example-nextjs/package.json
demos/react-multi-client/package.json
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/package.json
demos/react-native-web-supabase-todolist/package.json
demos/react-supabase-todolist-optional-sync/package.json
demos/react-supabase-todolist/package.json
demos/yjs-react-supabase-text-collab/package.json
packages/kysely-driver/package.json
packages/react-native/package.json
packages/web/package.json
pnpm-lock.yaml
tools/diagnostics-app/package.json

See: https://github.com/powersync-ja/powersync-sqlite-core/issues/47
Fix issue with remove operations resulting in dangling rows in some cases.

powersync-sqlite-core 0.3.6

---

.changeset/gentle-llamas-ring.md
packages/powersync-op-sqlite/android/build.gradle
packages/powersync-op-sqlite/powersync-op-sqlite.podspec

powersync-sqlite-core 0.3.6 for op-sqlite

---

README.md
packages/drizzle-driver/README.md
packages/drizzle-driver/src/utils/compilableQuery.ts

Follow-up PR for https://github.com/powersync-ja/powersync-js/pull/380

chore: Minor documentation improvements for introduction of Drizzle

---

.changeset/sixty-penguins-unite.md
packages/drizzle-driver/package.json
pnpm-lock.yaml

Addresses problem that was tackled in https://github.com/powersync-ja/powersync-js/pull/402. Using `^0.35.2` wasn't sufficient as it would cap at `<0.36.0`. Per Semver docs `Allows changes that do not modify the left-most non-zero element in the [major, minor, patch] tuple.`.
Tested as a dev release on their side.

chore: drizzle-orm as peer dependency

---

.changeset/hip-mugs-beam.md
packages/drizzle-driver/src/sqlite/db.ts

drizzle-orm supports a [casing](https://orm.drizzle.team/docs/sql-schema-declaration#camel-and-snake-casing) option to support defining schema in the following format (without explicit column name):
```
export const users = sqliteTable('users', {
id: integer(),
firstName: varchar()
})
```
This PR makes `wrapPowerSyncWithDrizzle` supports this as well:
```
export const db = wrapPowerSyncWithDrizzle(powerSyncDb, {
schema: drizzleSchema,
casing: 'snake_case'
});
```

allow using drizzle-orm casing option

---

.changeset/curly-poets-explode.md
demos/react-native-web-supabase-todolist/README.md
packages/web/README.md
packages/web/bin/powersync.js
packages/web/package.json
pnpm-lock.yaml

Some platforms/projects like react-native-web require configuration of the webworkers, which include copying assets from the dist directory of `@powersync/web` to somewhere like `public`. This PR introduces a CLI utility, which can in the future house other CLI commands.

feat: Web CLI utility for copying assets from node_modules to public

---

.changeset/tasty-birds-lay.md
demos/vue-supabase-todolist/package.json
packages/web/src/db/adapters/wa-sqlite/WASQLiteDBAdapter.ts
packages/web/src/db/adapters/web-sql-flags.ts
pnpm-lock.yaml

Overrides the default `temp_store` value for web to be `memory`. Additionally an option has been added to `WebSQLOpenFactoryOptions` to change this behaviour.  This will change will affect all projects as the default has been `file` up until now for web projects.

Added `temporaryStorage` option to WASQLiteOpenFactory.

---

.changeset/brown-moose-chew.md
packages/tanstack-react-query/package.json
packages/tanstack-react-query/src/hooks/useQuery.ts
packages/tanstack-react-query/tests/tsconfig.json
packages/tanstack-react-query/tests/useQuery.test.tsx
packages/tanstack-react-query/vitest.config.ts
pnpm-lock.yaml

Originally spurred on by https://github.com/powersync-ja/powersync-js/issues/417 where compilable queries would error without having a parameter value specified.
Added a default value in the hook and improved how the error state is tracked so that the infinite rendering issue doesn't happen anymore.
Also added basic unit tests.

fix: Tanstack error handling improvements

---

demos/django-react-native-todolist/android/build.gradle
demos/django-react-native-todolist/android/gradle.properties
demos/django-react-native-todolist/app.json
demos/django-react-native-todolist/package.json
demos/react-native-supabase-group-chat/android/build.gradle
demos/react-native-supabase-group-chat/android/gradle.properties
demos/react-native-supabase-group-chat/app.config.ts
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/android/build.gradle
demos/react-native-supabase-todolist/android/gradle.properties
demos/react-native-supabase-todolist/app.config.ts
demos/react-native-supabase-todolist/package.json
demos/react-native-web-supabase-todolist/android/build.gradle
demos/react-native-web-supabase-todolist/android/gradle.properties
demos/react-native-web-supabase-todolist/package.json
pnpm-lock.yaml

Bump demos due to RNQS upgrade against @powersync/react-native

chore: Bump Android minSdkVersion to 24

---

.changeset/green-waves-rescue.md
packages/attachments/package.json
packages/attachments/src/AbstractAttachmentQueue.ts
packages/attachments/tests/attachments/AttachmentQueue.test.ts
packages/attachments/vitest.config.ts
pnpm-lock.yaml

A user has a use-case where they only needed attachments to be uploaded. 
This change introduces a `downloadAttachments` option to the `AbstractAttachmentQueue` which defaults to `true`. If attachments should not be downloaded, the `downloadAttachments` option can be set to `false`.
- react-native-supabase-todolist
- react-native-web-supabase-todolist

Added option to download attachments

---

packages/drizzle-driver/tests/sqlite/watch.test.ts

Added two small unit tests to confirm that the issue reported [here](https://discord.com/channels/1138230179878154300/1307751877781356595) is definitely confirmed. These tests just insure that the relational entities returned in the response are objects/arrays of objects instead of unmapped value arrays as reported.
The existing watch tests only confirmed that watch works for trivial queries.

Drizzle watch relationship tests.

---

.changeset/strange-coins-leave.md
packages/drizzle-driver/src/index.ts
packages/drizzle-driver/src/utils/schema.ts
packages/drizzle-driver/tests/sqlite/schema.test.ts

drizzle-orm supports a [casing](https://orm.drizzle.team/docs/sql-schema-declaration#camel-and-snake-casing) option to support defining schema in the following format (without explicit column name):
```
export const users = sqliteTable('users', {
id: integer(),
firstName: varchar()
})
```
This PR makes toPowerSyncTable supports this as well:
```
export const AppSchema = new DrizzleAppSchema(drizzleSchema, {casing: 'snake_case'});
```

toPowerSyncTable support casing

---

.changeset/flat-toes-judge.md
packages/drizzle-driver/src/utils/schema.ts
packages/drizzle-driver/tests/sqlite/schema.test.ts

Drizzle schema supports some "mode," which behaves like a type in the JavaScript world and persists data as other types in SQLite.
For example, when using `text({mode: 'json'})`, in JavaScript it's JSON, but it stores data as text in SQLite.

make drizzle toPowerSyncTable support mode

---

.changeset/honest-mugs-yawn.md
packages/drizzle-driver/src/sqlite/db.ts

Resolved an issue where `.findMany` (and other multiple row results) queries had a type of `[][]` instead of `[]`. 
When checking the `db.watch(query, {onResult})`'s onResult type:
```
(results: {
id: string | null;
assets: {
id: string | null;
customer_id: string | null;
}[];
}[][]) => void
```
```
results: ({
id: string | null;
customer_id: string | null;
customer: {
...;
} | null;
} | undefined)[]) => void
```
```
(results: {
id: string | null;
assets: {
customer_id: string | null;
id: string | null;
}[];
}[]) => void
```
```
(results: ({
id: string | null;
customer_id: string | null;
customer: {
...;
} | null;
} | undefined)[]) => void
```

fix: Drizzle query returning an array-in-array type:

---

demos/angular-supabase-todolist/README.md
demos/react-native-supabase-todolist/README.md
demos/react-native-web-supabase-todolist/README.md
demos/react-supabase-todolist-optional-sync/README.md
demos/react-supabase-todolist/README.md
demos/vue-supabase-todolist/README.md

It appears this `https://docs.powersync.com/integration-guides/supabase` link has changed to `https://docs.powersync.com/integration-guides/supabase-+-powersync` so users were being redirected to the overview page. This fixes the links to map to the correct guide.

fix: supabase integration guide links

---

demos/angular-supabase-todolist/.gitignore
demos/angular-supabase-todolist/README.md
demos/angular-supabase-todolist/package.json
demos/angular-supabase-todolist/src/app/powersync.service.ts

We identified an issue with the Angular demo app when running on versions of “@journeyapps/wa-sqlite” newer than “0.4.2” and “@powersync/web” newer than “1.10.2”. The problem appears to stem from the newer wa-sqlite code not interacting correctly `with Angular’s Zone.js` dependecy.
As a workaround, you can copy the worker assets directly into the project and configure them at instantiation, similar to the approach used in the `react-native-web` demo. This approach resolves the issue. The README and code have been updated accordingly. Copying happens automatically as part of the serve/build steps in the demo.

Fixed angular demo app issues related to newer versions of web SDK and wa-sqlite.

---

packages/react-native/README.md

Add instructions for EAS builds

---

demos/django-react-native-todolist/app/views/todos/lists.tsx
demos/django-react-native-todolist/library/django/DjangoConnector.ts
demos/react-native-supabase-todolist/app/views/todos/edit/[id].tsx
demos/react-native-supabase-todolist/app/views/todos/lists.tsx
demos/react-native-supabase-todolist/ios/Podfile.lock
demos/react-native-supabase-todolist/library/supabase/SupabaseConnector.ts
demos/react-native-web-supabase-todolist/app/views/todos/edit/[id].tsx
demos/react-native-web-supabase-todolist/app/views/todos/lists.tsx
demos/react-native-web-supabase-todolist/library/supabase/SupabaseConnector.ts

Fix demos that expected `userID` to exist in `fetchCredentials` by adding a `userId` function to the connector.

fix: demos that expected userID in fetchCredentials

---

demos/react-native-supabase-todolist/app/_layout.tsx
demos/react-native-supabase-todolist/app/search_modal.tsx
demos/react-native-supabase-todolist/ios/Podfile.lock
demos/react-native-supabase-todolist/library/fts/fts_helpers.ts
demos/react-native-supabase-todolist/library/fts/fts_setup.ts
demos/react-native-supabase-todolist/library/fts/helpers.ts
demos/react-native-supabase-todolist/library/powersync/system.ts
demos/react-native-supabase-todolist/library/widgets/AutoCompleteWidget.tsx
demos/react-native-supabase-todolist/library/widgets/HeaderWidget.tsx
demos/react-native-supabase-todolist/library/widgets/SearchBarWidget.tsx
demos/react-native-supabase-todolist/package.json
pnpm-lock.yaml

This PR introduces Full-Text Search (FTS) functionality to the React Native Supabase Todo List demo. The implementation includes a search modal, an autocomplete search widget, and the integration of FTS capabilities for text-based searching.
- Full-Text Search (FTS) Integration and Setup
- Search modal
- Autocomplete search widget

Feat: FTS for react native supabase demo

---

packages/common/src/db/schema/Schema.ts
packages/common/tests/db/schema/Schema.test.ts

This PR addresses https://github.com/powersync-ja/powersync-js/issues/431#issuecomment-2522158014.
Add validation to the Schema constructor.
- We need to validate that the tables have a name here because a user could pass in an array Tables that don't have a name because they are using the V2 syntax.  Therefore, 'convertToClassicTables' won't be called on the tables resulting in a runtime error. 
Additional Tests:
- Added a new Schema test which checks that an error is thrown when a Schema is created incorrectly.

Add schema validation

---

packages/attachments/README.md

- Update schema definition and fix link in docs

Fix: Update attachments README

---

docs/babel.config.js
docs/docusaurus.config.ts
docs/package.json
pnpm-lock.yaml

This updates the docs to use docusarus 3.6, typedoc 0.27 and other minor updates. 
From Docusarus 3.6 we can now use a faster flag which improves build time. This has been enabled.
Rebuilding and re-running the docs showed no errors and clicking through the docs page appeared the same as previously.

chore: update docs deps

---

docs/utils/packageMap.ts

Rename JS Doc headings to use the frameworks nomenclature.

chore: rename docs headings

---

.changeset/moody-shoes-remain.md
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/client/sync/bucket/SqliteBucketStorage.ts

For a description of the issue and the fix, see: https://github.com/powersync-ja/powersync-sqlite-core/issues/54.

Avoid deleting the $local bucket on connect()

---

.changeset/metal-fans-argue.md
packages/powersync-op-sqlite/src/db/OPSQLiteConnection.ts
packages/powersync-op-sqlite/src/db/OPSqliteAdapter.ts

This PR addresses a timing issue in OPsqlite where the SQLite update hook triggers before the commit completes when performing single-write transactions (Resulting in `ps_crud` not being processed). As a result, `nextCrudItem` was returning undefined because the data was not yet committed at the time the hook fired. 
Using `react-native-quick-sqlite` as reference, updates are now batched and only flushed after a write lock is released.

fix: OP-sqlite write transaction single operation notification

---

.changeset/tame-singers-attack.md
demos/angular-supabase-todolist/package.json
demos/django-react-native-todolist/package.json
demos/example-capacitor/package.json
demos/example-electron/package.json
demos/example-nextjs/package.json
demos/react-multi-client/package.json
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/ios/Podfile.lock
demos/react-native-supabase-todolist/package.json
demos/react-native-web-supabase-todolist/ios/Podfile.lock
demos/react-native-web-supabase-todolist/package.json
demos/react-supabase-todolist-optional-sync/package.json
demos/react-supabase-todolist/package.json
demos/yjs-react-supabase-text-collab/package.json
packages/common/src/db/schema/Column.ts
packages/common/tests/db/schema/Table.test.ts
packages/common/tests/db/schema/TableV2.test.ts
packages/drizzle-driver/package.json
packages/kysely-driver/package.json
packages/powersync-op-sqlite/android/build.gradle
packages/powersync-op-sqlite/powersync-op-sqlite.podspec
packages/react-native/package.json
packages/web/package.json
pnpm-lock.yaml
tools/diagnostics-app/package.json

See: https://github.com/powersync-ja/powersync-sqlite-core/issues/52
- Update powersync-sqlite-core to 0.3.8 
- Increase limit on number of columns per table to 1999
Did a sweep over the react-native (RNQS/OPSqlite) and react (wa-sqlite) todo demos - works as expected.

powersync-sqlite-core 0.3.8

---

docs/package.json
docs/src/css/custom.css
packages/attachments/package.json
packages/common/package.json
packages/powersync-op-sqlite/package.json
packages/react-native/package.json
packages/react/package.json
packages/tanstack-react-query/package.json
packages/vue/package.json
packages/web/package.json
pnpm-lock.yaml

Add strikethrough to deprecated items in docs and update dependencies

feat(docs): add strikethrough to deprecated items

---

demos/react-supabase-todolist/src/app/router.tsx

This PR adds an auth guard that navigates the app to the login page if you navigate to a page that requires auth, or when the session expires.
Will apply this pattern to the other demos when this is accepted.

chore: Navigate to login page when accessing pages that require auth

---

.changeset/lovely-ligers-sleep.md
packages/drizzle-driver/src/index.ts
packages/drizzle-driver/src/sqlite/PowerSyncSQLiteBaseSession.ts
packages/drizzle-driver/src/sqlite/PowerSyncSQLiteDatabase.ts
packages/drizzle-driver/src/sqlite/PowerSyncSQLitePreparedQuery.ts
packages/drizzle-driver/src/sqlite/PowerSyncSQLiteSession.ts
packages/drizzle-driver/tests/setup/db.ts
packages/drizzle-driver/tests/sqlite/db.test.ts
packages/drizzle-driver/tests/sqlite/query.test.ts
packages/drizzle-driver/tests/sqlite/watch.test.ts

As part of https://github.com/powersync-ja/powersync-js/pull/463 locks were fixed for `React-Native`, which resulted in Drizzle transactions on RN projects to never be executed. This was due to the original Drizzle transaction implementation not using the correct lock context. I could confirm that this issue was happening for both `RNQS` and `OPSqlite`, but not for web.
`PowerSyncSQLiteSession` has been broken into `PowerSyncSQLiteSession` and `PowerSyncSQLiteBaseSession`, which ensures that a transaction uses the constrained LockContext instead of the db context (allowing transactions to be executed in the lock context).
This also makes room to eventually implement nested transactions/save points in `PowerSyncSqliteBaseSession`.
To verify this works across the board, I tested the fix for …

fix: Drizzle transactions not using lock context for React-Native

---

.changeset/lemon-moles-lie.md
packages/drizzle-driver/src/utils/schema.ts
packages/drizzle-driver/tests/sqlite/schema.test.ts

Adds support for custom types in the Drizzle/PowerSync schema definition - specifically with translating a Drizzle schema to PowerSync's app schema.
Bulk of the code was provided in this issue https://github.com/powersync-ja/powersync-js/issues/471.

feat: Drizzle - added support for custom column types in schema conversion

---

.changeset/thin-panthers-decide.md
packages/powersync-op-sqlite/src/db/OPSqliteAdapter.ts

Users can easily trigger two rollback calls in transactions which causes an exception message users can't do anything about. This PR simply silences the exception when this happens as we do in [dart](https://github.com/powersync-ja/sqlite_async.dart/blob/4ba51e5a5bc4b6e47c4a21b658776fdce30a0548/packages/sqlite_async/lib/src/utils/shared_utils.dart#L33).
Reference PR from RNQS: https://github.com/powersync-ja/react-native-quick-sqlite/pull/36

OPSLite: Silencing transactions that are reporting on failed rollbacks

---

.changeset/slow-crews-watch.md
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/react-native/src/db/PowerSyncDatabase.ts
packages/web/src/db/PowerSyncDatabase.ts
packages/web/tests/src/db/AbstractPowerSyncDatabase.test.ts
packages/web/tests/src/db/PowersyncDatabase.test.ts

Add `retryDelayMs` and `crudUploadThrottleMs` to `connect` so that the values can be dynamically changed on reconnecting. Deprecate `retryDelay` option in favor of `retryDelayMs`.
I ran the todolist react native demo and confirmed that the values used are from the connect method and added tests for web to confirm.

feat: add throttle and delay to connect

---

packages/powersync-op-sqlite/README.md

For large datasets on Android 12, the default temp store (file) may cause disk IO errors, in the past we resolved this for RNQS by setting a build flag to use the memory option.
This PR adds a readme entry on how a user can configure their package.json to set the option for OPSQLite, ideally there is a way for us to define this as part of the code generation.
Reference PR from RNQS: https://github.com/powersync-ja/react-native-quick-sqlite/pull/28

docs: OPSQLite large datasets on android 12 (Temporary store memory option)

---

.github/workflows/deploy-docs.yaml

The doc deploy action has started failing due to a deprecated action no longer working - the two actions I have bumped wrap that action.
I have updated to the versions recommended in the upload-pages-artifact v3 release here:  https://github.com/actions/upload-pages-artifact/releases
Example build failure: https://github.com/powersync-ja/powersync-js/actions/runs/13054794562
Writeup of deprecation: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

docs: Updated github action versions

---

.changeset/lovely-impalas-do.md
.changeset/slow-spiders-smash.md
.changeset/spotty-students-serve.md
packages/powersync-op-sqlite/README.md
packages/powersync-op-sqlite/src/db/OPSqliteAdapter.ts
packages/powersync-op-sqlite/src/db/SqliteOptions.ts
packages/web/src/db/adapters/wa-sqlite/WASQLiteConnection.ts
packages/web/src/db/adapters/wa-sqlite/WASQLiteDBAdapter.ts
packages/web/src/db/adapters/wa-sqlite/WASQLiteOpenFactory.ts
packages/web/src/db/adapters/web-sql-flags.ts
packages/web/src/db/sync/SharedWebStreamingSyncImplementation.ts
tools/diagnostics-app/src/library/powersync/ConnectionManager.ts

Add `cacheSizeKb` option for web and op-sqlite, defaulting to a 50MB max cache size (versus SQLite default of 2MB). This makes a big impact on IndexedDB - see https://github.com/powersync-ja/powersync-sqlite-core/pull/56#issuecomment-2642302992.
Also add both `temporaryStorage` and `cacheSizeKb` options for op-sqlite, now also defaulting op-sqlite to `PRAGMA temp_store = memory` (same as web), and a 50MB cache size. This removes the need for changing compile settings for op-sqlite for Android.
These are more effort to add for RNQS, so I haven't added it there yet (need to modify react-native-quick-sqlite itself).

Cache size & temp storage

---

.changeset/angry-pumpkins-double.md
.changeset/shiny-boxes-prove.md
packages/common/src/client/sync/stream/AbstractRemote.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/react-native/src/sync/stream/ReactNativeRemote.ts

This allows the fetch strategy to be configured, with the actual functionality addition being the `sequential` option.
When specifying `sequential`:
Instead of queueing up multiple sync events (10 originally) before applying them, which would lead to less round-trips - we are configuring the queue size to 1, meaning each event will get processed individually before asking for the next.
This results in less overhead processing of the netword events (pending items) and should free up the web socket for better keep alive acknowledgements.
Currently this resolves a known issue on slower devices with large sync datasets.

feat: Add FetchStrategy option to connect() for WebSockets

---

demos/react-native-supabase-group-chat/src/app/(app)/(chats)/g/create.tsx
demos/react-native-supabase-group-chat/src/app/(app)/contacts/index.tsx

A user reported the use of the removed/deprecated `executeAsync` function in a demo which has now be replaced by `execute`. Minor cleanup.
Original issue: https://github.com/powersync-ja/powersync-js/issues/509

chore: Removed last executeAsync usages in group-chat demo project.

---

packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/common/src/db/crud/SyncStatus.ts
packages/web/tests/stream.test.ts

This makes the API changes for bucket priorities consistent across the three SDKs that implement them:
1. List of entries for each priority status: `priorityStatusEntries` on `SyncStatus`.
2. Resolving the state for a priority: `statusForPriority` on `SyncStatus`.
3. Waiting for a sync to complete: Named `priority` argument on `PowerSyncDatabase.waitForFirstSync`.

Rename `priorityStatuses` -> `priorityStatusEntries`

---

.changeset/fluffy-rockets-breathe.md
demos/django-react-native-todolist/package.json
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/package.json
demos/react-native-web-supabase-todolist/package.json
packages/common/src/db/crud/SyncStatus.ts
pnpm-lock.yaml

The demos didn't correctly resolve to RNQS 2.4.1 on my side despite the PowerSync packages using them, at least when using `pnpm` on my side.
For `toSorted` in SyncStatus, it isn't available in React-Native without a polyfill, so I just replaced the shorthand with a similar implementation that is supported.

Updated demo's RNQS version and changed SyncStatus.ts to not depend on `toSorted`.

---

.changeset/loud-mangos-kick.md
package.json
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/db/DBAdapter.ts
packages/web/src/db/adapters/LockedAsyncDatabaseAdapter.ts
packages/web/tests/bucket_storage.test.ts
packages/web/tests/crud.test.ts
packages/web/tests/main.test.ts
packages/web/tests/multiple_instances.test.ts
packages/web/tests/offline.test.ts
packages/web/tests/on_change.test.ts
packages/web/tests/open.test.ts
packages/web/tests/performance.test.ts
packages/web/tests/schema.test.ts
packages/web/tests/schemav2.test.ts
packages/web/tests/stream.test.ts
packages/web/tests/uploads.test.ts
packages/web/tests/utils/generateConnectedDatabase.ts
packages/web/tests/utils/testDb.ts
packages/web/tests/watch.test.ts
packages/web/tests/watchSchemaChange.test.ts
packages/web/vitest.config.ts
pnpm-lock.yaml

The JS Web unit tests are still failing quite often.
This PR makes some improvements which cause the tests to pass in CI more often.
- Updated Vitest and Playwright to the latest versions
- Improved the structure for shared tests.  Shared tests for with/without webworkers and OPFS are now performed using shared test describing methods. The test suites are now separated for different DB configurations. Previously the tests would diverge on the individual test level.
- A subtle race condition in the closing of async DBAdapters has been fixed. This ensures a DBAdapter should be completely closed when `powersync.close` has been called.
- Vitest still tries to run unit tests concurrently, even if sequential is specified, this can cause locking timeouts. Testing DB generator methods have been …

Improve Tests

---

.changeset/mighty-guests-lick.md
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/web/tests/src/db/AbstractPowerSyncDatabase.test.ts

Because we're now reading from the `ps_sync_state` to restore the `lastSyncedAt` information, we need version 0.3.11 of the core extensions or newer. This adopts the version check accordingly.

Raise minimum version for core extension

---

.changeset/mighty-spies-fail.md
demos/django-react-native-todolist/package.json
demos/react-native-supabase-group-chat/package.json
demos/react-native-supabase-todolist/package.json
demos/react-native-web-supabase-todolist/package.json
packages/powersync-op-sqlite/android/build.gradle
packages/powersync-op-sqlite/powersync-op-sqlite.podspec
packages/react-native/package.json
packages/web/package.json
pnpm-lock.yaml

This updates the core extension to 0.3.12 by:
1. Updating the version referenced in the Gradle/CocoaPods build definition for `powersync-op-sqlite`.
2. Updating the dependency on `@journeyapps/wa-sqlite` for the web.
3. Updating the dependency on `@journeyapps/react-native-quick-sqlite` for react native.

Update core extension to 0.3.12

---

.changeset/modern-lobsters-sell.md

The original [PR](https://github.com/powersync-ja/powersync-js/pull/451) did not contain a changeset so the updated README did not reflect on npm.

Add changeset for attachment readme update

---

.changeset/tame-boats-hammer.md
packages/node/README.md

Add a section to the readme explaining that the package is in an Alpha release at the moment.

Add alpha release hints to node package

---

.changeset/grumpy-panthers-own.md
packages/node/package.json
packages/react-native/package.json
packages/web/package.json

Following the suggestion from @kobiebotha, this standardizes the package description for SDK entrypoint packages to "PowerSync ${Framework} SDK. Sync Postgres, MongoDB or MySQL with SQLite in your ${Framework} app".

Use consistent package descriptions for SDK packages

---

.changeset/slimy-glasses-jog.md
packages/react/src/hooks/useQuery.ts

Using the following snippet (originally reported [here](https://github.com/powersync-ja/powersync-js/issues/517)) that applies a filter in a useEffect to a query to make the result set smaller:
```
function GetUsers() {
const [userFilter, setUserFilter] = useState<string>()
let query = db.selectFrom("User").selectAll()
if (userFilter) {
query = query.where("id", "=", userFilter)
}
const { data } = useQuery(query)
console.log("GetUsers result", userFilter, data.length)
useEffect(() => {
setUserFilter("500")
}, [])
return <Text>Data length: {data.length}</Text>
}
```
The first query that was fired without the filter from the `if` finishes last meaning query order and result order ends up not being the same. Giving the following output:
```
GetUsers result 500 0
GetUsers result 500 0 …
```

Fix useQuery race condition for initial query.

---

.changeset/slimy-mice-invite.md
packages/attachments/src/AbstractAttachmentQueue.ts

The attachment queue always pointed to the hardcoded `attachments` table. This allows the developer to override the target table. 
Alternative approach to https://github.com/powersync-ja/powersync-js/pull/523, which was originally reported in https://github.com/powersync-ja/powersync-js/issues/522.
Update: Verified working on the reporter's side.

feat: Added attachmentTableName option

---

.changeset/new-doors-unite.md
packages/web/src/db/adapters/wa-sqlite/WASQLiteConnection.ts
packages/web/tests/encryption.test.ts

Got the following error when building an encryption demo:
It seems that executing the cache_size pragma before the encryption pragma causes this issue. Simply reordered, and verified this fix via unit tests.

fix: Web encryption crashing on init.

---

README.md
demos/example-vite-encryption/README.md
demos/example-vite-encryption/package.json
demos/example-vite-encryption/src/index.html
demos/example-vite-encryption/src/index.js
demos/example-vite-encryption/vite.config.ts
pnpm-lock.yaml

Small demo that shows how to setup powersync with an encryption key. When loading the page a prompt pops up asking for the key, which will be used to create/open the database.
https://github.com/user-attachments/assets/417c70e9-1f33-4cf3-a332-3ba5bf1af542

demo: Vite Web Encryption Example

---

.changeset/lazy-moons-prove.md
.changeset/nice-steaks-approve.md
packages/common/src/client/SQLOpenFactory.ts
packages/node/package.json
packages/node/src/db/BetterSQLite3DBAdapter.ts
packages/node/src/db/SqliteWorker.ts
packages/node/tests/PowerSyncDatabase.test.ts
packages/node/tests/utils.ts
pnpm-lock.yaml

As a parameter, `dbLocation` controls the directory we use to store the database file. When used, it should always point at an existing directory because we're not creating it beforehand. This is not mentioned in the JSDoc, so this adds a sentence about that.
For the node SDK, this also improves the error message when misusing `dbLocation` by including the solution (creating the directory).

Improve documentation on `dbLocation` and related error message on node

---

.changeset/khaki-pears-add.md
packages/web/src/db/adapters/WorkerWrappedAsyncDatabaseConnection.ts

This PR resolves an issue related to sequential `connect()` calls breaking all syncing and never reaching a `connected` state.
Two typical scenarios that can cause this is switching client parameters and React's `StrictMode` which does multiple calls of hooks like `useEffect`.
This PR ensures that locks used for internal connection sharing are unique.
Alternative to https://github.com/powersync-ja/powersync-js/pull/545
Thanks @simolus3 for suggesting this approach.

Navigator locks are now aquired with a random/unique key.

---

.changeset/good-ghosts-rush.md
packages/web/bin/powersync.js

Aims to resolve https://github.com/powersync-ja/powersync-js/issues/540.
In monorepos the node_modules directory is not always at `cwd`.

chore: Resolving `node_modules` via require.resolve for `copy-assets`

---

.changeset/fast-cobras-repeat.md
packages/tanstack-react-query/package.json
pnpm-lock.yaml

Simple peer dependency bump.
Resolves https://github.com/powersync-ja/powersync-js/issues/491

Bumping tanstack peer dependency to ^5.70.0

---

.changeset/moody-fans-knock.md
packages/kysely-driver/package.json
pnpm-lock.yaml

Kysely recently release a new version [0.28](https://github.com/kysely-org/kysely/releases/tag/0.28.0) and I would like to add support for it in Powersync.
Currently, updating Kysely alone throws a bunch of type errors.
This is my first contribution attempt to Powersync, please let me know what other changes and information I can provide to help get this PR merged!

chore: update Kysely version in driver package

---

.changeset/hip-lamps-draw.md
.changeset/thick-lies-invent.md
.changeset/thirty-humans-shop.md
demos/example-node/src/main.ts
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/client/sync/stream/AbstractRemote.ts
packages/node/README.md
packages/node/package.json
packages/node/src/db/PowerSyncDatabase.ts
packages/node/src/sync/stream/NodeRemote.ts
pnpm-lock.yaml

Introduced support for specifying proxy environment variables for the connection methods. HTTP will use `EnvHttpProxyAgent`(see https://github.com/nodejs/undici/pull/2994/files#diff-e75b15c5fd859828aa0413c608603d1152bd54320aabd8ec8f73b023c924d0db) from `undici` and Websockets will use `proxy-agent`. In both cases the libraries automatically use the correct env variable. For HTTP this will typically be `HTTP_PROXY` or `HTTPS_PROXY` and for Websockets it will be  `WS_PROXY` or `WSS_PROXY`, with other known options also available.   
The HTTP dispatcher can be overridden with the `dispatcher` `connect()` option:
```
await db.connect(new DemoConnector(), {
connectionMethod: SyncStreamConnectionMethod.HTTP,
dispatcher: new MyAgent()
});
```
To support specifying a custom option for the connect …

feat: Add Proxy support for `@powersync/node`

---

.changeset/polite-news-sneeze.md
packages/common/src/client/sync/bucket/SqliteBucketStorage.ts
packages/node/tests/sync.test.ts
packages/node/tests/utils.ts

After we receive a (partial) checkpoint complete and have validated checksums, we set `last_op` to the `last_op_id` of the checkpoint for involved buckets.
Due to an ignored filter in `syncLocalDatabase`, we were raising `last_op` even for buckets with lower priorities when receiving a partial completion for a higher priority. Having a wrong value in `last_op_id` is a problem when the sync stream gets reset without completing a full checkpoint afterwards, because we use that value to create the next request when reconnecting.

Fix missing filter when setting `last_op`

---

packages/common/src/db/crud/SyncProgress.ts

This fixes a small typo in the documentation for the `SyncProgress` class (`th` -> `the`).

Fix typo in sync progress docs

---

.changeset/giant-ladybugs-dress.md
packages/common/src/client/sync/bucket/CrudEntry.ts
packages/common/src/db/schema/Schema.ts
packages/common/src/db/schema/Table.ts
packages/common/tests/db/schema/Schema.test.ts
packages/common/tests/db/schema/Table.test.ts
packages/common/tests/db/schema/TableV2.test.ts
packages/node/tests/crud.test.ts

This exposes the new table options introduced in version 0.3.13 of the core extension, namely:
- `include_old` (either a boolean or an array of column names): Adds an `old` entry to the `ps_crud.data` JSON object that includes old values for updates.
- `include_old_only_when_changed`: Skip unchanged values from updates.
- `include_metadata`: Adds a `_metadata` column that can be written to for updates. It's reported through `CrudEntry.metadata` afterwards.
- `ignore_empty_update`: Don't create `ps_crud` entries for `UPDATE` statements that didn't change any values. 
Most of this feature is tested in the core extension, this adds a few simple tests ensuring we forward options correctly.

Schema options

---

packages/node/download_core.js

When `download_core.js` is invoked and a local copy of the core extension already exists, the script currently does nothing. That's fine when `download_core.js` is used as an install script because we expect that directory to be immutable after the install script ran.
Especially when developing on this SDK though, the current behavior can easily lead to situations where the core extension is outdated. This fixes the script to:
1. Generate a sha256 hash for the local file if it exists.
2. Compare that to the expected hash we carry for every core build the script may have to download.
3. Only skip downloading the file if the hash matches.
4. (there's also a post-download hash check now, you never know)
To be able to update the expected hashes after update, the script has an `update_hashes` …

`download_core.js`: Download file again if outdated

---

.changeset/cuddly-news-carry.md
tools/diagnostics-app/src/library/powersync/RecordingStorageAdapter.ts

The diagnostics app overrides SqliteBucketStorage to track some metadata. This was not updated when we implemented bucket priorities, resulting in checksum failures in the diagnostics app when bucket priorities are used.
The symptoms would be repeated logs like below, and never completing the sync.
```
[PowerSyncStream] Partial checkpoint complete 1
[SqliteBucketStorage] validateChecksums priority, checkpoint, result item undefined, {...}
[SqliteBucketStorage] Checksums failed for ...
[SqliteBucketStorage] done deleting bucket
```
This issue was specific to the diagnostics app, and did not affect any other SDK clients.
The deployed diagnostics app version was a little outdated, and not affected by this issue.

[Diagnostics App] Fix partial checkpoints (bucket priorities)

---

.changeset/honest-melons-laugh.md
packages/web/src/worker/sync/SharedSyncImplementation.ts

This was causing worker remote logs not to be broadcasted to the individual tabs' logs. Missing parameter on construction of the WebRemote in SharedSyncImplementation - `this.logger` will be set to `this.broadcastLogger` when the `broadcastLogs` flag is true (defaults to true).
After this change you can see the remote logs:
| log call | Log in tab's console |
|--------|--------|
| ![Screenshot 2025-05-15 at 10 18 17](https://github.com/user-attachments/assets/d9aca1c6-1c02-4f87-bcb1-1a9ec7245b1a) | ![Screenshot 2025-05-15 at 10 21 45](https://github.com/user-attachments/assets/2c7add01-a507-49fa-8061-ac051a4dee26) |

fix: Broadcast logger not being being passed to WebRemote

---

.changeset/cool-yaks-allow.md
.changeset/shiny-rules-invent.md
packages/common/src/client/sync/stream/AbstractRemote.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/web/src/db/sync/SharedWebStreamingSyncImplementation.ts
packages/web/src/worker/sync/AbstractSharedSyncClientProvider.ts
packages/web/src/worker/sync/SharedSyncImplementation.ts

Improved credentials management and error handling. Credentials are invalidated when they expire or become invalid based on responses from the PowerSync service. The frequency of credential fetching has been reduced as a result of this work.
For web we need to communicate over the comlink from the worker to the main tab that invalidation needs to happen.
Follows a similar pattern applied to PowerSync Dart.
Alternative approach to https://github.com/powersync-ja/powersync-js/pull/528

feat: Fetch credentials on token expiry/401

---

demos/example-nextjs/package.json
pnpm-lock.yaml

This should avoid react version mismatches.

Added caret (^) to both the react and react-dom dependencies in example-nextjs demo.

---

.changeset/slimy-cougars-rush.md
packages/common/src/client/sync/bucket/CrudEntry.ts
packages/node/tests/crud.test.ts

This makes `CrudEntry.toJSON()` include previous values and metadata, with the same keys for serialization as thos used in the Dart SDK.

Include metadata and previous values in CRUD entry JSON

---

.changeset/weak-chairs-complain.md
demos/react-native-supabase-todolist/library/powersync/system.ts
packages/react-native/src/db/PowerSyncDatabase.ts
packages/react-native/src/sync/bucket/ReactNativeBucketStorageAdapter.ts

For reasons I don't fully understand, the array buffers we get from the RSocket package can't be passed to RNQS directly (it doesn't recognize them as array buffers and binds parameters to null). So, we copy once more.
I've also used this to benchmark syncing 1M rows once more (using RNQS with the demo todolist app and again with the barebones op-sqlite app). The sync is with an app launched using `pnpm ios` on an simulator and a sync service + Postgres on localhost. I've reinstalled the app before each run. Note that the checkpoint applies extremely slowely on the todolist app because there are FTS5 triggers.
| Implementation | Time downloading | Time until data availability |
|-----------------|----------------------------------------|----------------------------------------|
| Baseline …

Fix new sync client with RNQS

---

.changeset/healthy-carrots-exercise.md
packages/common/src/client/sync/bucket/BucketStorageAdapter.ts
packages/common/src/client/sync/bucket/SqliteBucketStorage.ts
packages/web/tests/bucket_storage.test.ts

This removes logic in the bucket adapters related to compaction. We check at runtime that we're talking to version 0.3.11 of the core extension or later, so compacion operations are a guaranteed no-op that will be handled during regular sync instead.

Remove unused compaction logic

---

.changeset/tall-dolphins-sleep.md
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/node/tests/sync.test.ts

When the Rust client exports timestamps for the sync status, they're encoded as UTC seconds. `new Date` expects milliseconds though, and so the reported time used to be close to 1970 instead of the actual time.

Fix `lastSyncedAt` values with Rust client

---

.changeset/new-readers-dance.md
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/node/tests/sync.test.ts

With the JavaScript sync client, the promise returned by `connect()` is supposed to return after a connection has been established and the first sync line received (this is different to all our other SDKs, which return as soon as a connection task has been set up and started).
The way this behavior is implemented is that `connect()` registers a `statusUpdated` handler that completes once the `connected` status is changed. This works with the JavaScript client because it only changes fields that actually need to change. With Rust however, we receive a full `SyncStatus` snapshot instead (so we call `updateSyncStatus` with a complete status that will always have `connected` set - even to `false` initially).
The workaround feels a bit hacky, but since something like `statusUpdated` doesn't …

Fix `connect()` resolving early with Rust client

---

packages/powersync-op-sqlite/README.md

This links the workaround we recommend as a metro config when using the React Native SDK without Expo in the OP-sqlite adapter readme as well. The reason is that we've seen users get weird errors when adopting OP-sqlite without Expo in their existing projects, and the metro configuration we suggest seems to fix them.

Mention metro workaround for op-sqlite

---

.changeset/twenty-cats-cry.md
packages/common/src/db/crud/SyncProgress.ts

This uses a relative import because the absolute one can't be resolved by tsc for users depending on `@powersync/common`.

Fix broken `src/` import in `SyncProgress.ts`

---

.changeset/orange-baboons-work.md
packages/common/src/client/sync/stream/AbstractRemote.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/common/src/client/sync/stream/streaming-sync-types.ts
packages/common/src/utils/async.ts
packages/react-native/src/sync/stream/ReactNativeRemote.ts
packages/web/tests/stream.test.ts
packages/web/tests/utils/MockStreamOpenFactory.ts
packages/web/tests/utils/generateConnectedDatabase.ts

This ports the Rust approach of listening to CRUD upload completions to the JS client as well.
Instead of polling on a promise that resolves on a CRUD upload, we register a listener on completed uploads as a callback. This callback then schedules another round of the main loop handling sync lines, triggering another attempt to apply the checkpoint. This mirrors the "merged streams" approach we have in Dart (and also in the Rust client).
To support this, I had to remove the non-raw methods from `AbstractRemote` - we need custom line mapping to inject the parsed upload complete notifications.

Dont block on crud uploads

---

packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/node/src/db/PowerSyncDatabase.ts
packages/node/tests/sync.test.ts

Fix regression from #661. What would happen:
1. "Could not apply checkpoint due to local data. We will retry applying the checkpoint after that upload is completed." -> sets `pendingValidatedCheckpoint` to checkpoint A.
2. Receive a `data`  and `checkpoint_complete` message -> validates checkpoint B.
3. Crud upload complete -> queues a `crud_upload_completed` message.
4. Attempts `this.applyCheckpoint(pendingValidatedCheckpoint)` with checkpoint A. Checkpoint A is no longer valid, so this results in "Checksums failed", and re-downloading the data.
Was not part of a stable release, so no changeset required.

Clear pendingValidatedCheckpoint on new checkpoints

---

.changeset/bright-snakes-clean.md
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/common/src/db/schema/RawTable.ts

This:
1. Removes a concrete example for raw tables from the changelog - the feature is more complicated than that and requires e.g. custom triggers to detect local writes. So it's better to link to the [upcoming docs page](https://github.com/powersync-ja/powersync-docs/pull/198).
2. Explicitly mentions that the Rust client is required for raw tables.
3. Issues a warning log if the JS client is used with raw tables.

Improve docs for raw tables

---

.changeset/fresh-laws-join.md
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/client/sync/bucket/SqliteBucketStorage.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
packages/node/src/db/PowerSyncDatabase.ts
packages/react-native/src/db/PowerSyncDatabase.ts
packages/web/src/db/PowerSyncDatabase.ts

1. Propagate logger instance from PowerSyncDatabase to the StreamingSyncImplementation and Remote implementations in the various SDKs. This means we now actually use the `logger` passed in the constructor, at the cost of not having a more specific prefix like `[PowerSyncStream]`.
2. Include database name in the default logger, i.e. `PowerSyncDatabase[test.db]`. This helps debugging issues when multiple databases are used.
3. Add some logging for write checkpoints / upload complete.
4. Cleanup for some other log messages.

Improve logging

---

.changeset/bright-yaks-pump.md
demos/react-supabase-todolist/src/app/views/layout.tsx
packages/common/src/client/sync/stream/AbstractRemote.ts

This is a slightly alternative approach to https://github.com/powersync-ja/powersync-js/pull/668. The fix here declares the `stream` early which should avoid the `(TypeError: Cannot read property 'close' of undefined')` issue highlighted in the linked PR. Additionally the changes here allow the WebSocket initial connection request to be aborted without waiting for it to reject/complete.
I've added a button to change the connection status to the React Supabase Todolist demo. I've also testing a slow connection attempt by running the PowerSync service locally with a paused attached debugger.

WebSocket Timeout Fix

---

.changeset/fair-buttons-deliver.md
packages/adapter-sql-js/package.json
pnpm-lock.yaml

Small dependency bump for adapter-sql-js package.
See upstream change https://github.com/powersync-ja/powersync-sql-js/pull/5

fix(adapter-sql-js): Updated sql-js upstream version to support rust sync implementation

---

.changeset/nice-dragons-smile.md
.github/workflows/test-simulators.yaml
packages/common/src/client/AbstractPowerSyncDatabase.ts
packages/common/src/utils/async.ts
packages/node/tests/PowerSyncDatabase.test.ts
packages/react-native/README.md

Sometimes, users want a batch of data to upload while also ensuring that that batch respects transaction boundaries. At the moment, we don't really have APIs for that, because:
- `getCrudBatch()` returns a batch of items with a flexible size limit, but doesn't respect transaction boundaries (so it's possible to accidentally upload half of a transaction).
- `getNextCrudTransaction()` returns a complete transaction, but nothing more. It will also always return the oldest transaction, so you can't call `getNextCrudTransaction()` multiple times to get more than one.
This adds `getCrudTransactions()`, an async iterable that starts with the oldest transaction and then keeps on yielding more transactions until the iterator is closed. This gives users a tool to compose batches with flexible sizes …

Add `getCrudTransactions()` returning an async generator

---

.changeset/slow-melons-raise.md
packages/react/src/hooks/watched/useQuery.ts
packages/react/src/hooks/watched/useSingleQuery.ts
packages/react/src/hooks/watched/useWatchedQuery.ts
packages/react/src/hooks/watched/useWatchedQuerySubscription.ts
packages/react/src/hooks/watched/watch-utils.ts
packages/react/tests/useQuery.test.tsx

In `useQuery`, we used to invoke the inner `useWatchedQuery` or `useSingleQuery` hooks depending on options passed to the `useQuery` hook.
This violates the [rules of hooks](https://react.dev/reference/rules/rules-of-hooks), because they must be invoked unconditionally. Mixing them like this can trip up the internal state of `useEffect` hooks and others, causing all kinds of issues that are hard to debug.
So to avoid this, we add an `active: boolean` parameter to the internal hooks to conditionally disable them. Then, we can just call both hooks all the time since the inactive one won't actually do anything. I've added a test that fails with the old implementation but works with the new one.

Avoid calling hooks conditionally

---

.changeset/honest-penguins-worry.md
packages/common/src/client/sync/stream/AbstractRemote.ts
packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts

When disconnecting and connecting frequently, it is currently possible for the Rust sync clients to get locked in a frozen state if the `StreamingSyncClient` is disconnected/aborted before it has connected.
This can happen if:
- The client is triggered for a connect
- A disconnect is requested shortly after
- The `StreamingSyncImplementation`'s `AbortController` is marked as aborted, but we nest the `AbortController` [here](https://github.com/powersync-ja/powersync-js/blob/2f6153c95c9b24e5dca6213c3654e55eb8577cff/packages/common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts#L905). 
- For WebSocket requests, we usually check if the provided `AbortSignal` has been aborted before making the request (and we throw), but due to the wrapped controller used in the Rust …

Fix: Rust Client Disconnect Race

---

.changeset/real-dolls-peel.md
packages/common/src/client/watched/processors/AbstractQueryProcessor.ts
packages/common/src/client/watched/processors/DifferentialQueryProcessor.ts
packages/common/src/client/watched/processors/OnChangeQueryProcessor.ts
packages/react/tests/useQuery.test.tsx
packages/vue/tests/useQuery.test.ts

This fixes a reported issue where a query that is busy fetching handles a query/parameter change incorrectly. It would go from reporting isFetching=true, to false, to immediately true again. With the expected behaviour being that it remained true during the transition instead. This also caused `isLoading` to become false prematurely.
This was caused by the stale query handler not aborting correctly.
Example erroneous output, where the param changes from 0->1:
```
{param: '0', dataLength: 0, isFetching: true, isLoading: true}
{param: 1, dataLength: 0, isFetching: true, isLoading: true}
{param: 1, dataLength: 0, isFetching: false, isLoading: false} <--- we don't expect this step
{param: 1, dataLength: 0, isFetching: true, isLoading: false}
{param: 1, dataLength: 1, isFetching: false, …
```

fix: prevent isFetching flickering during query parameter changes

---

.changeset/young-bananas-heal.md
packages/common/src/client/triggers/TriggerManager.ts

This updates the API doc example for `TriggerManager`.`trackTableDiff` to use `withDiff` for accessing the `DIFF` instead of the `getAll` method. The DIFF is only available with the ` trackTableDiff` method.

Trigger Docs Update

---

.changeset/chilly-penguins-learn.md
.changeset/empty-glasses-camp.md
.github/workflows/test-simulators.yaml
packages/common/src/client/watched/WatchedQuery.ts
packages/common/src/client/watched/processors/AbstractQueryProcessor.ts
packages/common/src/client/watched/processors/DifferentialQueryProcessor.ts
packages/common/src/client/watched/processors/OnChangeQueryProcessor.ts
packages/react/src/hooks/watched/useWatchedQuery.ts
packages/react/tests/useQuery.test.tsx
packages/react/vitest.config.ts
packages/web/tests/watch.test.ts

This PR fixes several bugs and regressions introduced with [Incrementally Watched Queries](https://github.com/powersync-ja/powersync-js/pull/614).  
For background, see [this Discord thread](https://discord.com/channels/1138230179878154300/1411678544085651496/1411678544085651496).  
This addresses a race condition that could occur when `updateSettings` was called multiple times on the same `WatchedQuery` instance.  
The changes improve how `AbortController` lifecycles are managed, ensuring that updates from linked queries do not execute simultaneously.  
Previously, this could cause `isFetching` to briefly report `false` before toggling back to `true` when query parameters changed.  
In some cases, `isFetching` was reported as `false` immediately after changing query parameters: before …

WatchedQuery Bug Fixes

---

.changeset/young-maps-grin.md
tools/diagnostics-app/src/app/page.tsx
tools/diagnostics-app/src/components/widgets/LoginDetailsWidget.tsx
tools/diagnostics-app/src/library/powersync/TokenConnector.ts

This will allow us to generate an API token and open the diagnostics tool with that token from dashboard for example.
https://github.com/user-attachments/assets/d5e4d35a-6ae1-425c-955c-bfe4af126c2f

feat: Added support for a "token" query parameter in diag tool.

---

.changeset/ninety-bears-own.md
packages/react/src/hooks/streams.ts
packages/react/tests/streams.test.tsx

When passing streams to `useQuery`, one currently needs to spell out `name` and `parameters` explicitly. 
As [a user reported](https://discord.com/channels/1138230179878154300/1422138173907144724/1422252801358299277), it would be quite nice if the objects returned by `syncStream()` could also be used for this. That is almost the case already, a small `undefined` vs `null` issue is the only reason they're not compatible.
This fixes a type and adds a test ensuring we can pass `syncStream()` instances to hooks.

Allow using `syncStream()` instances with hooks
