powersync-ja/powersync-js

- packages/powersync-sdk-react-native/README.md
- packages/powersync-sdk-react-native/package.json
- Update homepage link for NPM package
- Readme terminology: cloud service -> service
> Minor updates: Readme and NPM package listing

- .github/workflows/deploy-docs.yaml
- package.json
Some of the commands were not properly carried over in `package.json` and in the github actions
* Added `release` command to `package.json`
* Added docs build step to docs github action
> fix: github actions

- packages/powersync-attachments/package.json
- packages/powersync-react/package.json
- packages/powersync-sdk-common/package.json
- packages/powersync-sdk-react-native/package.json
- packages/powersync-sdk-web/CHANGELOG.md
- packages/powersync-sdk-web/package.json
Update references in `package.json`
Pointed reference to new repo name
> chore: update reference in package.json

- demos/nextjs-supabase-todolist/README.md
Update link in nextjs-supabase-todolist README.md with new monorepo location
> Update link in nextjs-supabase-todolist README.md

- README.md
Fix markdown formatting issue in Yjs link
> Update README.md link formatting

- README.md
Remove git submodules reference from main README
> Remove git submodules reference from README

- demos/react-native-supabase-group-chat/.gitignore
- demos/react-native-supabase-group-chat/src/lib/config.ts
- demos/react-native-supabase-group-chat/src/lib/connector.ts
- demos/react-native-supabase-group-chat/src/lib/database.types.ts
- demos/react-native-supabase-group-chat/src/lib/date.ts
- demos/react-native-supabase-group-chat/src/lib/schema.ts
- demos/react-native-supabase-group-chat/src/lib/supabase.ts
- demos/react-native-supabase-group-chat/src/lib/uuid.ts
Lib folder is missing
* Re-add lib folder to demo
* Add rule to include it in gitignore of demo
> fix: add lib folder

- README.md
- packages/kysely-driver/README.md
- Reference the package on the monorepo README
- Add beta release note
> Readme updates for the Kysely release

- demos/angular-supabase-todolist/package.json
- demos/nextjs-supabase-todolist/src/library/powersync/AppSchema.ts
- demos/yjs-nextjs-supabase-text-collab/src/library/powersync/AppSchema.ts
- demos/yjs-nextjs-supabase-text-collab/src/library/powersync/SupabaseConnector.ts
- packages/kysely-driver/tests/setup/db.ts
- packages/kysely-driver/tests/setup/types.ts
- packages/kysely-driver/tests/sqlite/db.test.ts
- packages/kysely-driver/tsconfig.json
- packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
- packages/powersync-sdk-common/src/client/AbstractPowerSyncOpenFactory.ts
- packages/powersync-sdk-common/src/client/sync/bucket/CrudEntry.ts
- packages/powersync-sdk-common/src/client/sync/bucket/SyncDataBucket.ts
- packages/powersync-sdk-common/src/client/sync/stream/AbstractStreamingSyncImplementation.ts
- packages/powersync-sdk-common/src/db/crud/SyncStatus.ts
- packages/powersync-sdk-common/src/db/crud/UploadQueueStatus.ts
- packages/powersync-sdk-common/src/db/schema/Index.ts
- packages/powersync-sdk-common/src/db/schema/Schema.ts
- packages/powersync-sdk-common/src/db/schema/Table.ts
- packages/powersync-sdk-common/src/db/schema/TableV2.ts
- packages/powersync-sdk-common/src/index.ts
- packages/powersync-sdk-common/src/utils/BaseObserver.ts
- packages/powersync-sdk-common/src/utils/mutex.ts
- packages/powersync-sdk-common/tsconfig.json
- packages/powersync-sdk-react-native/src/sync/stream/ReactNativeRemote.ts
- packages/powersync-sdk-react-native/src/sync/stream/ReactNativeStreamingSyncImplementation.ts
- packages/powersync-sdk-react-native/tsconfig.json
- packages/powersync-sdk-web/tests/schemav2.test.ts
- packages/powersync-sdk-web/tsconfig.json
- pnpm-lock.yaml
Add table and schema type enhancements
* Added changes to Schema to allow for using the new table structure
* Added a TablesV2 that users can use to define a table with typing
* Enforced strict null check
Attachments package PR will need to be updated to allow for using `TableV2` which will need to be looked at at a later date and due to this the react native demo cannot yet be updated/
> feat(common-sdk): add schema and table enhancements

- .changeset/angry-brooms-attend.md
- packages/kysely-driver/README.md
This updates the readme with some links for defining schema definitions using `TableV2`.
> [Readme] Updated Readme for kysely-driver

- demos/example-nextjs/CHANGELOG.md
- demos/react-native-supabase-group-chat/CHANGELOG.md
- demos/react-native-supabase-todolist/CHANGELOG.md
- demos/react-supabase-todolist/CHANGELOG.md
- demos/react-supabase-todolist/README.md
- demos/react-supabase-todolist/vite.config.mts
- demos/yjs-react-supabase-text-collab/CHANGELOG.md
- Updated outdated Next.js references
- Rename changelog headers to the demo names
- Improve getting started instructions for react-supabase-todolist demo
> Minor fixes

- packages/powersync-sdk-common/src/client/AbstractPowerSyncDatabase.ts
Looked at the Flutter reference (https://pub.dev/documentation/powersync/latest/sqlite_async/SqliteQueries/executeBatch.html) and similar existing methods in the SDK (e.g. `.execute`) for wording/naming guidelines.
> Update executeBatch description and param names for consistency

- docs/docusaurus.config.ts
- docs/package.json
- pnpm-lock.yaml
* Enable search
* Configured and enabled Algolia
* Fixed title name for SEO
* Updated packages
* Run `cd docs && pnpm build && pnpm start` from root
* Search in the top right hand
> feat(docs): add search

- .changeset/eighty-lies-fetch.md
This is for the previous PR which had changes for FTS.
> chore: Bump minor versions for common and web sdk

- .changeset/clever-kiwis-lay.md
I confused the packages during the renaming.
> chore: fixed changelog mistake

- packages/react/src/hooks/useQuery.ts
Fix react hook not updating due to table not updating
> fix: react hook not updating data

- .changeset/witty-eyes-count.md
- demos/react-native-supabase-todolist/app/views/todos/lists.tsx
> fix(react-native-supabase-todo): Replaced <p> tag with <Text>

- pnpm-lock.yaml
Updates the PNPM lockfile to fix [bug](https://github.com/powersync-ja/powersync-js/actions/runs/9160289344/job/25182598675).
This should be included in a post version script in future.
> [Chore] Update lockfile

- docs/docusaurus.config.ts
Use code block for definition
This 
changes to this
> chore(docs): add code block option

- docs/docusaurus.config.ts
Remove unnecessary sources from the docs
**Before**
**After**
> chore(docs): remove sources

- pnpm-lock.yaml
Release failed due to the lock file needing an update.
> Updated lock file.

- README.md
- packages/react-native/README.md
- packages/web/README.md
- Update root Readme banner image
- Update PowerSync description
> Readme updates

- .changeset/bright-cooks-change.md
Changed text in changeset entry.
> Minor changelog update for client params introduction

- packages/kysely-driver/README.md
- packages/kysely-driver/tests/setup/db.ts
- packages/react/README.md
- packages/web/tests/crud.test.ts
- tools/diagnostics-app/src/library/powersync/ConnectionManager.ts
- tools/diagnostics-app/src/library/powersync/DynamicSchemaManager.ts
- tools/diagnostics-app/src/library/powersync/RecordingStorageAdapter.ts
* Improve React README
* Make changes to use PowerSyncDatabase that were missed
> chore: update readme and update to PowerSyncDatabase

- packages/attachments/package.json
- packages/common/package.json
- packages/react/package.json
- packages/vue/package.json
Homepages are pointing to a non existent page. This fixes that by pointing them to the powersync website.
> chore: update homepages

- .changeset/slow-news-report.md
- demos/angular-supabase-todolist/extra-webpack.config.js
- demos/angular-supabase-todolist/package.json
- demos/vue-supabase-todolist/package.json
- packages/common/package.json
- packages/kysely-driver/package.json
- packages/react-native/package.json
- packages/react/package.json
- packages/vue/package.json
- packages/web/package.json
- pnpm-lock.yaml
- tools/diagnostics-app/package.json
There are build issues and typescript version issues when running the Angular demo
* Updated to Angular 18
* Added additional webpack config to fix build issues
* Updated to the latest TypeScript where packages were using ^
> fix: issues starting angular app

- .changeset/config.json
- .changeset/odd-beers-tease.md
- .dockerignore
- .github/workflows/diagnostics-image-build.yaml
- .github/workflows/diagnostics-image-release.yaml
- tools/diagnostics-app/Dockerfile
- tools/diagnostics-app/nginx.conf
- tools/diagnostics-app/package.json
Automates a docker image build for the diagnostics app, using nginx to serve the static assets.
See discussion on https://github.com/powersync-ja/self-host-demo/issues/23.
> Docker image for diagnostics-app

- .changeset/afraid-bulldogs-check.md
- packages/common/src/client/sync/bucket/SqliteBucketStorage.ts
Update `deleteBucket` function to use new operation and simplify it
Replaced internals for `deleteBucket` with new operation
> chore(common): improve deleteBucket function

- .changeset/great-walls-juggle.md
- packages/common/package.json
- packages/common/src/db/schema/Table.ts
- packages/common/src/db/schema/TableV2.ts
- packages/common/tests/db/schema/TableV2.test.ts
- pnpm-lock.yaml
Users currently only see an error for maxmium number of columns at runtime. This adds a check so that they would see it on Table creation.
* Added checks to `TableV2` and added testing
* Added a check to `Table` (left out tests since we are going to remove this in next major release)
* Updated to latest `vitest`
> chore(common): add max column check

- demos/example-vite/src/index.js
- demos/example-webpack/src/index.js
Fix column not being imported error 
Tested building and running both demos
> fix: demo import

- README.md
- packages/react-native/README.md
- packages/web/README.md
> README MySQL updates

- .changeset/orange-jeans-shake.md
Changeset was not included in the previous navigator lock PR, this includes it.
> chore: add changeset

- demos/angular-supabase-todolist/src/app/supabase.service.ts
- demos/django-react-native-todolist/library/django/DjangoConnector.ts
- demos/react-multi-client/src/library/SupabaseConnector.ts
- demos/react-native-supabase-group-chat/src/lib/connector.ts
- demos/react-native-supabase-todolist/library/supabase/SupabaseConnector.ts
- demos/react-native-web-supabase-todolist/library/supabase/SupabaseConnector.ts
- demos/react-supabase-todolist-optional-sync/src/library/powersync/SupabaseConnector.ts
- demos/react-supabase-todolist/src/library/powersync/SupabaseConnector.ts
- demos/vue-supabase-todolist/src/library/powersync/SupabaseConnector.ts
- demos/yjs-react-supabase-text-collab/src/library/powersync/SupabaseConnector.ts
- demos/yjs-react-supabase-text-collab/supabase/functions/merge-document-updates/index.ts
- packages/web/src/db/sync/SharedWebStreamingSyncImplementation.ts
Clean up connectors by removing unused fields `expiredAt`, `client` and `userID`
> chore: clean up connectors

- demos/react-native-supabase-todolist/library/powersync/AppSchema.ts
- demos/react-native-web-supabase-todolist/library/powersync/AppSchema.ts
- packages/attachments/README.md
- packages/attachments/package.json
- pnpm-lock.yaml
Clean up attachments readme to use latest `Table` syntax. Update react native demos to use latest `Table` syntax.
> chore: clean up attachments readme and update demos

- vitest.workspace.ts
This adds a simple vitest workspace configuration file including all packages with a `vitest.config.ts` file in their root directory.
Using this workspace file helps with some editors (I'm using the vitest plugin in VS code for example, which requires a configuration file to deal with large workspaces).
> Add vitest workspace configuration

- .changeset/hot-weeks-thank.md
- demos/django-react-native-todolist/ios/Podfile.lock
- demos/django-react-native-todolist/package.json
- demos/react-native-barebones-opsqlite/ios/Podfile.lock
- demos/react-native-supabase-group-chat/package.json
- demos/react-native-supabase-todolist/package.json
- packages/node/download_core.js
- packages/powersync-op-sqlite/android/build.gradle
- packages/powersync-op-sqlite/powersync-op-sqlite.podspec
- packages/react-native/package.json
- packages/web/package.json
- pnpm-lock.yaml
This updates the PowerSync SQLite core extension to version 0.3.14 in preparation for sync progress and schema options.
> Update core extension to 0.3.14

- .changeset/kind-months-tickle.md
- packages/drizzle-driver/README.md
This bumps the Drizzle integration to a Beta release
> Drizzle Beta
